---
settings:
  name: Astra Control Service
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  filter:
    label: Cloud-Provider
    default: Alle Cloud-Provider
    options:
    - name: Amazon Web Services
      alias: Amazon Web Services
      id: aws
    - name: Google Cloud
      alias: Google Cloud
      id: gcp
    - name: Microsoft Azure
      alias: Azure
      id: azure
  rss_page: release-notes/whats-new.html
  langs: de-de,us-en,ja-jp,zh-cn,zh-tw,ko-kr,fr-fr
sidebar:
  entries:
  - title: Astra Control Service Dokumentation
    url: "/index.html"
  - section: release-notes
  - section: get-started
  - section: use
  - title: Automatisierung mit der Astra Control REST-API
    url: "/automation.html"
  - section: learn
  - section: support
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Los geht's
    links:
    - title: Erfahren Sie mehr über den Astra Control Service
      url: "/get-started/intro.html"
    - title: Schnellstart
      url: "/get-started/quick-start.html"
    - title: Häufig gestellte Fragen
      url: "/get-started/faq.html"
  - title: Nutzen Sie Den Astra Control Service
    links:
    - title: Management von Applikationen
      url: "/use/manage-apps.html"
    - title: Schützen Sie Ihre Applikationen
      url: "/use/protect-apps.html"
    - title: Migrieren einer Applikation
      url: "/use/clone-apps.html"
    - title: Abrechnung einrichten
      url: "/use/set-up-billing.html"
  - title: Verwenden Sie die Astra Control REST-API
    links:
    - title: Los geht's
      url: https://docs.netapp.com/us-en/astra-automation/get-started/before_get_started.html
    - title: API-Referenz
      url: https://docs.netapp.com/us-en/astra-automation/reference/api_reference.html
    - title: API-Workflows
      url: https://docs.netapp.com/us-en/astra-automation/workflows/workflows_before.html
  - title: Demos Tutorials
    links:
    - title: Videos des Astra Control Service
      url: "/get-started/videos.html"
  - title: Astra Control Center
    links:
    - title: Einführung in das Astra Control Center
      url: https://docs.netapp.com/us-en/astra-control-center/concepts/intro.html
    - title: Was ist neu
      url: https://docs.netapp.com/us-en/astra-control-center/release-notes/whats-new.html
    - title: Schnellstart
      url: https://docs.netapp.com/us-en/astra-control-center/get-started/quick-start.html
  - title: Lösungen im Überblick
    links:
    - title: DataStax Enterprise Apache Cassandra mit Astra Control
      url: https://cloud.netapp.com/hubfs/SB-4134-0321-DataStax-Cassandra-Guide%20(1).pdf
    - title: PostgreSQL DBaaS mit Astra Control
      url: https://cloud.netapp.com/hubfs/SB-4122-0221-PostgresSQL-DBaaS-with-Astra%20(2).pdf
    - title: MySQL DBaaS mit Astra Control
      url: https://cloud.netapp.com/hubfs/SB-4110-0221-MySQL-Astra%20(2).pdf
    - title: Vereinfachung des Lifecycle Managements von Jenkins
      url: https://cloud.netapp.com/hubfs/SB-4100-Jenkins%20(2).pdf
  - title: Blogs Community
    links:
    - title: Astra Discord-Kanal
      url: https://discord.gg/NetApp
    - title: Astra Control Blog
      url: https://cloud.netapp.com/blog/topic/astra
    - title: Astra Control – vereinfachtes App-Datenmanagement für die Hybrid Cloud
      url: https://cloud.netapp.com/blog/blg-astra-control-simplifying-kubernetes-application-data-management-for-the-hybrid-cloud
    - title: Kubernetes Hub in Cloud Central
      url: https://cloud.netapp.com/kubernetes-hub
product-family:
  name: Astra
  repo: astra-family
  sidebar_label: Die komplette Astra Dokumentation
