---
settings:
  name: Astra Control Service
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  filter:
    label: Cloud-Provider
    default: Alle Cloud-Provider
    options:
    - name: Amazon Web Services
      alias: Amazon Web Services
      id: aws
    - name: Google Cloud
      alias: Google Cloud
      id: gcp
    - name: Microsoft Azure
      alias: Azure
      id: azure
  rss_page: release-notes/whats-new.html
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr
sidebar:
  entries:
  - title: Astra Control Service Dokumentation
    url: "/index.html"
  - section: release-notes
  - section: get-started
  - section: learn
  - section: use
  - title: Automatisierung mit der Astra Control REST-API
    url: "/automation.html"
  - section: support
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: Astra
  repo: astra-family
  sidebar_label: Die komplette Astra Dokumentation
