---
sidebar: sidebar 
permalink: learn/aws-storage.html 
keywords: service level, storage class, storage classes, pv size, persistent volume size, volume size, bandwidth, performance 
summary: 'Astra Control Service kann Amazon Elastic Block Store (EBS) oder Amazon FSX für NetApp ONTAP als Storage-Back-Ends für Elastic Kubernetes Service (EKS) Cluster nutzen. Sie sollten verstehen, wie Sie mithilfe einer Storage-Klasse und einer persistenten Volume-Größe Ihre Performance-Ziele erreichen können.' 
---
= Storage-Klassen und Performance für AWS Cluster
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/learn/


[role="lead"]
Astra Control Service kann Amazon Elastic Block Store (EBS), Amazon FSX for NetApp ONTAP oder NetApp Cloud Volumes ONTAP als Storage-Backend für Amazon Elastic Kubernetes Service (EKS)-Cluster verwenden.



== Amazon Elastic Block Store (EBS)

Ihre Cluster können eine Schnittstelle mit EBS über Container Storage Interface (CSI)-Treiber (Container Storage Interface) erstellen. Wenn Sie EBS als Speicher-Backend für EKS-Cluster verwenden, können Sie einige Speicherklassenparameter konfigurieren. Weitere Informationen über die Bedeutung der Parameter und deren Konfiguration finden Sie unter https://["Die Kubernetes-Dokumentation"^].

Sie können mit EBS mehrere verschiedene Volume-Typen verwenden:

* Solid State-Laufwerke (SSD)
* Festplattenlaufwerke (HDD)
* Vorherige Generation


Weitere Informationen zu den einzelnen Volume-Typen und ihrer Performance finden Sie unter https://["Die Dokumentation zu Amazon EBS"^]. Preisinformationen finden Sie unter https://["Amazon EBS Preis"^].



== Amazon FSX für NetApp ONTAP

Wenn Sie FSX für NetApp ONTAP als Storage-Backend für AWS Cluster verwenden, hängt die I/O-Performance von der Konfiguration des Dateisystems und den Eigenschaften Ihrer Workloads ab. Weitere Informationen zur Performance von NetApp ONTAP finden Sie unter FSX https://["Amazon FSX für die Performance von NetApp ONTAP"^]. Preisinformationen finden Sie unter https://["Amazon FSX für NetApp ONTAP-Preise"^].



== NetApp Cloud Volumes ONTAP

Genaue Informationen zur Konfiguration von NetApp Cloud Volumes ONTAP, einschließlich Performance-Empfehlungen, finden Sie im https://["NetApp Cloud Volumes ONTAP-Dokumentation"^].
