---
sidebar: sidebar 
permalink: use/log-in.html 
keywords: logging in, log in, sign in, signing in, BlueXP, netapp BlueXP, user account 
summary: Astra Control Service ist über eine SaaS-basierte Benutzeroberfläche über astra.netapp.io zugänglich. 
---
= Melden Sie sich beim Astra Control Service an
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Der Zugriff auf Astra Control Service erfolgt über eine SaaS-basierte Benutzeroberfläche über die von Ihnen zu bedienende Benutzeroberfläche https://astra.netapp.io[].


TIP: Sie können sich mit Single Sign-On über Anmeldedaten aus Ihrem Unternehmensverzeichnis (föderierte Identität) anmelden. Weitere Informationen erhalten Sie im https://cloud.netapp.com/help-center["Hilfe-Center"^] Und wählen Sie dann *Cloud Central Anmelde-Optionen*.

.Bevor Sie beginnen
* link:../get-started/register.html["Eine BlueXP Benutzer-ID"].
* link:../get-started/register.html["Ein neues Astra Control Konto"] Oder link:manage-users.html["Einladung zu einem bestehenden Account"].
* Einen unterstützten Webbrowser.
+
Astra Control Service unterstützt aktuelle Versionen von Firefox, Safari und Chrome mit einer Mindestauflösung von 1280 x 720.



.Schritte
. Öffnen Sie einen Webbrowser, und gehen Sie zu https://astra.netapp.io[].
. Melden Sie sich mit Ihren NetApp BlueXP Zugangsdaten an.

