---
sidebar: sidebar 
permalink: use/manage-buckets.html 
keywords: bucket, buckets, add buckets, change default bucket, default, default bucket, remove bucket, delete bucket, S3, s3, storage, object storage, object store, store, object 
summary: Managen Sie die Buckets, die Astra für Backups und Klone verwendet, indem Sie zusätzliche Buckets hinzufügen und den Standard-Bucket für die Cluster in Ihrem Cloud-Provider ändern. 
---
= Buckets verwalten
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Sie können die Buckets managen, die Astra für Backups und Klone verwendet. Sie können zusätzliche Buckets hinzufügen, vorhandene Buckets entfernen und den Standard-Bucket für die Kubernetes-Cluster in einer Cloud-Instanz ändern.

Nur Eigentümer und Administratoren können Buckets managen.



== So verwendet Astra Control Buckets

Wenn Sie Ihr erstes Kubernetes-Cluster für eine Cloud-Instanz managen, erstellt Astra Control Service den ersten Bucket dafür link:manage-cloud-instances.html["Cloud-Instanz"^].

Sie können einen Bucket manuell als Standardbucket für eine Cloud-Instanz festlegen. Astra Control Service verwendet diesen Bucket standardmäßig für die Backups und Klone, die Sie auf einem beliebigen gemanagten Cluster in dieser Cloud-Instanz erstellen (Sie können einen anderen Bucket für Backups auswählen). Wenn Sie einen Live-Klon einer Applikation von einem der gemanagten Cluster in einer Cloud-Instanz in ein anderes Cluster ausführen, verwendet Astra Control Service den Standard-Bucket für die Cloud-Quell-Instanz, um den Klonvorgang auszuführen.

Sie können denselben Bucket wie den Standard-Bucket für mehrere Cloud-Instanzen festlegen.

Sie können aus beliebigen Buckets auswählen, wenn Sie eine Schutzrichtlinie erstellen oder ein Ad-hoc-Backup starten.


TIP: Astra Control Service überprüft vor dem Start eines Backups oder Klons, ob auf einen Ziel-Bucket zugegriffen werden kann.



== Vorhandene Buckets anzeigen

In der Liste der Buckets, die für Astra Control Service verfügbar sind, können Sie ihren Status ermitteln und den Standard-Bucket (sofern definiert) für Ihre Cloud-Instanz identifizieren.

Ein Bucket kann einen der folgenden Zustände haben:

Ausstehend:: Nachdem Sie einen Bucket hinzugefügt haben, wird er im ausstehenden Status gestartet, während Astra Control ihn erkennt.
Verfügbar:: Der Eimer ist für Astra Control verfügbar.
Entfernt:: Der Bucket ist momentan nicht einsatzbereit. Bewegen Sie die Maus über das Statussymbol, um zu ermitteln, was das Problem ist.
+
--
Wenn ein Bucket den Status „entfernt“ aufweist, können Sie ihn immer noch als Standard-Bucket festlegen und ihn einem Sicherungszeitplan zuweisen. Wenn der Bucket jedoch zum Start eines Datensicherungsvorgangs nicht im Status „verfügbar“ steht, schlägt dieser Vorgang fehl.

--


.Schritt
. Gehen Sie zu *Buckets*.
+
Die Liste der für Astra Control Service verfügbaren Buckets wird angezeigt.





== Fügen Sie einen zusätzlichen Bucket hinzu

Sie können jederzeit weitere Buckets hinzufügen. Dadurch können Sie beim Erstellen einer Sicherungsrichtlinie oder beim Starten eines Ad-hoc-Backups zwischen Buckets wählen und den Standard-Bucket ändern, den eine Cloud-Instanz verwendet.

Sie können die folgenden Buckets hinzufügen:

* Amazon Web Services
* Allgemein S3
* Google Cloud Platform
* Microsoft Azure
* NetApp ONTAP S3
* NetApp StorageGRID S3


.Bevor Sie beginnen
* Der Name eines vorhandenen Buckets.
* Die Anmeldeinformationen für den Bucket, der Astra Control Service die Berechtigungen zur Verwaltung des Buckets zur Verfügung stellt


ifdef::azure[]

* Wenn sich Ihr Bucket in Microsoft Azure befindet:
+
** Der Bucket muss zur Ressourcengruppe _astra-Backup-rg_ gehören.
** Wenn die Performance der Azure Storage-Kontoinstanz auf „Premium“ eingestellt ist, muss die Einstellung „Premium-Kontotyp“ auf „Block-Blobs“ gesetzt werden.




endif::azure[]

.Schritte
. Gehen Sie zu *Buckets*.
. Wählen Sie *Hinzufügen* und folgen Sie den Anweisungen, um den Eimer hinzuzufügen.
+
** *Typ*: Wählen Sie Ihren Cloud-Anbieter.
** *Vorhandener Bucket-Name*: Geben Sie den Namen des Buckets ein.
** *Beschreibung*: Geben Sie optional eine Beschreibung des Eimers ein.




ifdef::azure[]

* *Storage-Konto* (nur Azure): Geben Sie den Namen Ihres Azure-Speicherkontos ein. Dieser Bucket muss zur Ressourcengruppe namens _astra-Backup-rg_ gehören.


endif::azure[]

ifdef::aws[]

* *S3-Servername oder IP-Adresse* (nur AWS- und S3-Bucket-Typen): Geben Sie den vollständig qualifizierten Domainnamen des S3-Endpunkts ein, der Ihrer Region entspricht, ohne `https://`. Siehe https://docs.aws.amazon.com/general/latest/gr/s3.html["Die Amazon-Dokumentation"^] Finden Sie weitere Informationen.


endif::aws[]

* *Select credentials*: Geben Sie die Zugangsdaten ein, die Astra Control Service mit den Berechtigungen zur Verwaltung des Buckets zur Verfügung stellen. Die Informationen, die Sie bereitstellen müssen, hängen vom Bucket-Typ ab.
+
.. Wählen Sie *Hinzufügen*, um den Eimer hinzuzufügen.




.Ergebnis
Der Bucket wird mit Astra Control Service hinzugefügt. Sie können diesen Bucket jetzt auswählen, wenn Sie eine Schutzrichtlinie erstellen oder ein Ad-hoc-Backup durchführen. Sie können diesen Bucket auch als Standardbucket für eine Cloud-Instanz festlegen.



== Ändern des Standard-Bucket

Sie können den Standard-Bucket für eine Cloud-Instanz ändern. Astra Control Service verwendet diesen Bucket standardmäßig für Backups und Klone. Jede Cloud-Instanz verfügt über einen eigenen Standard-Bucket.


NOTE: Astra Control weist keinem Cloud-Instanz automatisch einen Standard-Bucket zu. Sie müssen einen Standard-Bucket für eine Cloud-Instanz manuell festlegen, bevor Sie Applikationsklonvorgänge zwischen zwei Clustern durchführen.

.Schritte
. Gehen Sie zu *Cloud-Instanzen*.
. Wählen Sie das Konfigurationsmenü in der Spalte *Aktionen* für die Cloud-Instanz, die Sie bearbeiten möchten.
. Wählen Sie *Bearbeiten*.
. Wählen Sie in der Liste der Buckets den Bucket aus, der als Standard-Bucket für diese Cloud-Instanz verwendet werden soll.
. Wählen Sie *Aktualisieren*.




== Entfernen Sie einen Bucket

Sie können einen Eimer entfernen, der nicht mehr verwendet wird oder nicht ordnungsgemäß ist. Dies könnte Sie nutzen, um die Konfiguration Ihres Objektspeicher einfach und aktuell zu halten.

Sie können keinen Standard-Bucket entfernen. Wenn Sie diesen Bucket entfernen möchten, wählen Sie zuerst einen anderen Bucket als Standard aus.

.Bevor Sie beginnen
* Sie sollten vor Beginn sicherstellen, dass keine Backups für diesen Bucket ausgeführt oder abgeschlossen wurden.
* Sie sollten prüfen, ob der Bucket nicht für geplante Backups verwendet wird.


Wenn dies der Fall ist, können Sie nicht fortfahren.

.Schritte
. Gehen Sie zu *Buckets*.
. Wählen Sie im Menü *Aktionen* die Option *Entfernen*.
+

NOTE: Astra Control stellt zunächst sicher, dass es keine Planungsrichtlinien gibt, die den Bucket für Backups verwenden und dass keine aktiven Backups im Bucket vorhanden sind, den Sie entfernen möchten.

. Geben Sie „Entfernen“ ein, um die Aktion zu bestätigen.
. Wählen Sie *Ja, entfernen Sie den Eimer*.




== Weitere Informationen

* https://docs.netapp.com/us-en/astra-automation/index.html["Verwenden Sie die Astra Control API"^]

