---
sidebar: sidebar 
permalink: use/manage-credentials.html 
keywords: invite users, add users, remove users, delete users 
summary: Fügen Sie Ihrem Konto Anmeldedaten für Cloud-Provider jederzeit hinzu und entfernen Sie sie. Astra Control verwendet diese Zugangsdaten für die Bereitstellung von Ressourcen in Ihrem Namen. 
---
= Anmeldeinformationen hinzufügen und entfernen
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Fügen Sie Ihrem Konto Anmeldedaten für Cloud-Provider jederzeit hinzu und entfernen Sie sie. Astra Control verwendet diese Zugangsdaten, um einen Kubernetes Cluster, die Applikationen auf dem Cluster zu erkennen und Ressourcen in Ihrem Auftrag bereitzustellen.

Beachten Sie, dass alle Benutzer in Astra Control dieselben Anmeldedaten verwenden.



== Anmeldedaten hinzufügen

Die häufigste Möglichkeit, Anmeldeinformationen zum Astra Control hinzuzufügen, ist, wenn Sie Cluster verwalten, aber Sie können auch Anmeldeinformationen von der Konto-Seite hinzufügen. Die Anmeldedaten stehen dann zur Verfügung, wenn Sie zusätzliche Kubernetes-Cluster managen.

.Was Sie benötigen
ifdef::aws[]

* Bei Amazon Web Services sollten Sie über die JSON-Ausgabe der Anmeldedaten für das IAM-Konto verfügen, die zum Erstellen des Clusters verwendet werden. link:../get-started/set-up-amazon-web-services.html["Erfahren Sie, wie Sie einen IAM-Benutzer einrichten"].


endif::aws[]

ifdef::gcp[]

* Für GKE sollten Sie die Schlüssel-Datei für ein Servicekonto haben, das über die erforderlichen Berechtigungen verfügt. link:../get-started/set-up-google-cloud.html["Erfahren Sie, wie Sie ein Service-Konto einrichten"].


endif::gcp[]

ifdef::azure[]

* Bei AKS sollten Sie die JSON-Datei haben, die die Ausgabe aus der Azure CLI enthält, wenn Sie den Service-Principal erstellt haben. link:../get-started/set-up-microsoft-azure-with-anf.html["Erfahren Sie, wie Sie einen Service-Principal einrichten"].
+
Außerdem benötigen Sie Ihre Azure Abonnement-ID, wenn Sie sie nicht zur JSON-Datei hinzugefügt haben.



endif::azure[]

.Schritte
. Wählen Sie *Konto > Anmeldeinformationen*.
. Wählen Sie *Anmeldeinformationen Hinzufügen*.


ifdef::azure[]

. Wählen Sie *Microsoft Azure*.


endif::azure[]

ifdef::gcp[]

. Wählen Sie *Google Cloud Platform*.


endif::gcp[]

ifdef::aws[]

. Wählen Sie *Amazon Web Services*.


endif::aws[]

. Geben Sie einen Namen für die Anmeldeinformationen ein, der sie von anderen Anmeldeinformationen in Astra Control unterscheidet.
. Geben Sie die erforderlichen Anmeldedaten ein.


ifdef::azure[]

. *Microsoft Azure*: Geben Sie Astra Control Details über Ihren Azure Service Principal durch das Hochladen einer JSON-Datei oder durch Einfügen des Inhalts dieser JSON-Datei aus Ihrer Zwischenablage.
+
Die JSON-Datei sollte beim Erstellen des Service-Principal die Ausgabe aus der Azure CLI enthalten. Sie können auch Ihre Abonnement-ID angeben, damit sie automatisch in Astra Control hinzugefügt wird. Andernfalls müssen Sie die ID manuell eingeben, nachdem Sie den JSON bereitgestellt haben.



endif::azure[]

ifdef::gcp[]

. *Google Cloud Platform*: Stellen Sie die Kontoschlüsseldatei des Google Cloud-Dienstes entweder durch das Hochladen der Datei oder durch Einfügen des Inhalts aus Ihrer Zwischenablage bereit.


endif::gcp[]

ifdef::aws[]

. *Amazon Web Services*: Geben Sie die Zugangsdaten für den Amazon Web Services IAM-Benutzer entweder durch das Hochladen der Datei oder durch Einfügen der Inhalte aus Ihrer Zwischenablage an.


endif::aws[]

. Wählen Sie *Anmeldeinformationen Hinzufügen*.


.Ergebnis
Die Anmeldedaten stehen jetzt zur Verfügung, wenn Sie ein Cluster zu Astra Control hinzufügen.



== Anmeldedaten entfernen

Entfernen Sie die Anmeldeinformationen jederzeit aus einem Konto. Sie sollten erst nach dem Entfernen von Anmeldeinformationen verwenden link:unmanage.html["Verwalten aller Cluster aufheben"], Sofern Sie die Anmeldeinformationen nicht ändern (siehe <<Anmeldeinformationen drehen>>).


NOTE: Der erste Satz von Anmeldeinformationen, die Sie Astra Control hinzufügen, wird immer verwendet, da Astra Control die Zugangsdaten für die Authentifizierung im Backup-Bucket verwendet. Diese Anmeldedaten sollten am besten nicht entfernt werden.

.Schritte
. Wählen Sie *Konto > Anmeldeinformationen*.
. Wählen Sie die Dropdown-Liste in der Spalte *Status* für die Anmeldeinformationen aus, die Sie entfernen möchten.
. Wählen Sie *Entfernen*.
. Geben Sie den Namen der Anmeldeinformationen ein, um das Löschen zu bestätigen, und wählen Sie dann *Ja, Anmeldeinformationen entfernen*.


.Ergebnis
Astra Control entfernt die Anmeldeinformationen aus dem Konto.



== Anmeldeinformationen drehen

Sie können die Anmeldeinformationen in Ihrem Konto ändern. Wenn Sie die Anmeldeinformationen drehen, drehen Sie sie während eines Wartungsfensters, wenn keine Backups ausgeführt werden (geplant oder auf Anforderung).

.Schritte
. Entfernen Sie die vorhandenen Anmeldeinformationen, indem Sie die Schritte unter ausführen <<Anmeldedaten entfernen>>.
. Fügen Sie die neuen Anmeldeinformationen hinzu, indem Sie die Schritte unter ausführen <<Anmeldedaten hinzufügen>>.
. Alle Buckets aktualisieren, um die neuen Anmeldedaten zu verwenden:
+
.. Wählen Sie in der linken Navigationsleiste *Buckets* aus.
.. Wählen Sie die Dropdown-Liste in der Spalte *Aktionen* für den Bucket aus, den Sie bearbeiten möchten.
.. Wählen Sie *Bearbeiten*.
.. Wählen Sie im Abschnitt *Anmeldeinformationen auswählen* die neuen Anmeldeinformationen aus, die Sie Astra Control hinzugefügt haben.
.. Wählen Sie *Aktualisieren*.
.. Wiederholen Sie die Schritte *b* bis *e* für alle übrigen Eimer auf Ihrem System.




.Ergebnis
Astra Control nutzt die Zugangsdaten für den neuen Cloud-Provider.
