---
sidebar: sidebar 
permalink: use/restore-apps.html 
keywords: restore app, restoring an app, restore an app, restore, ontap-nas-economy, disruptive, migration 
summary: Astra Control kann Ihre Applikationskonfiguration und Ihren persistenten Storage aus einem Snapshot oder Backup wiederherstellen. Persistente Storage-Backups werden aus Ihrem Objektspeicher übertragen, sodass die Wiederherstellung aus bestehenden Backups am schnellsten abgeschlossen wird. 
---
= Wiederherstellung von Applikationen
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Astra Control kann Ihre Applikation aus einem Snapshot oder einem Backup wiederherstellen. Das Wiederherstellen aus einem vorhandenen Snapshot erfolgt schneller, wenn die Anwendung auf dasselbe Cluster wiederhergestellt wird. Sie können die Astra Control UI oder verwenden https://docs.netapp.com/us-en/astra-automation/index.html["Die Astra Control API"^] Zur Wiederherstellung von Applikationen.


NOTE: Wenn Sie einem Ausführungs-Hook einen Namespace-Filter hinzufügen, der nach einer Wiederherstellung oder einem Klonvorgang ausgeführt wird, und die Wiederherstellungs- oder Klonquelle und das Ziel in verschiedenen Namespaces liegen, wird der Namespace-Filter nur auf den Ziel-Namespace angewendet.

.Bevor Sie beginnen
* *Schützen Sie Ihre Anwendungen zuerst*: Es wird dringend empfohlen, dass Sie einen Snapshot oder ein Backup Ihrer Anwendung vor der Wiederherstellung machen. Auf diese Weise können Sie aus dem Snapshot oder Backup klonen, wenn die Wiederherstellung nicht erfolgreich war.
* *Zieldatenträger prüfen*: Wenn Sie eine andere Speicherklasse wiederherstellen, stellen Sie sicher, dass die Speicherklasse den gleichen persistenten Zugriffsmodus für Volumes verwendet (z. B. ReadWriteMany). Der Wiederherstellungsvorgang schlägt fehl, wenn der Zugriffsmodus des Ziel-persistenten Volumes anders ist. Wenn das persistente Quell-Volume beispielsweise den RWX-Zugriffsmodus verwendet, wählen Sie eine Ziel-Storage-Klasse aus, die RWX nicht bereitstellen kann, wie z. B. Azure Managed Disks, AWS EBS, Google Persistent Disk oder `ontap-san`Wird dazu führen, dass der Wiederherstellungsvorgang fehlschlägt. Weitere Informationen zu den Zugriffsmodi für persistente Volumes finden Sie im https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes["Kubernetes"^] Dokumentation.
* *Planung des Platzbedarfs*: Wenn Sie eine in-Place-Wiederherstellung einer Applikation durchführen, die NetApp ONTAP Storage nutzt, kann sich der von der wiederhergestellten Applikation genutzte Speicherplatz verdoppeln. Nachdem Sie eine in-Place-Wiederherstellung durchgeführt haben, entfernen Sie alle unerwünschten Snapshots aus der wiederhergestellten Applikation, um Speicherplatz freizugeben.
* *Unterstützte Storage Class Treiber*: Astra Control unterstützt die Wiederherstellung von Backups mit Speicherklassen, die von den folgenden Treibern unterstützt werden:
+
** `ontap-nas`
** `ontap-nas-economy`
** `ontap-san`
** `ontap-san-economy`


* *(nur ontap-nas-Economy-Treiber) Backups und Wiederherstellungen*: Vor dem Backup oder der Wiederherstellung einer App, die eine von der unterstützte Storage-Klasse verwendet `ontap-nas-economy` Überprüfen Sie, ob der link:../use/protect-apps.html#enable-backup-and-restore-for-ontap-nas-economy-operations["Das snapshot Verzeichnis auf dem ONTAP Storage-Backend ist verborgen"]. Das Ausblenden dieses Verzeichnisses kann zu einem Verlust des Zugriffs auf Ihre Anwendung führen, insbesondere wenn es NFSv3 verwendet.


[CAUTION]
====
Die Durchführung einer in-Place-Wiederherstellung in einer Anwendung, in der Ressourcen mit einer anderen Anwendung geteilt werden, kann unbeabsichtigte Ergebnisse haben. Alle Ressourcen, die von den Applikationen gemeinsam genutzt werden, werden ersetzt, wenn eine in-Place-Wiederherstellung für eine der Applikationen durchgeführt wird.

====
.Schritte
. Wählen Sie *Anwendungen* und dann den Namen einer App aus.
. Wählen Sie im Menü Optionen in der Spalte Aktionen die Option *Wiederherstellen* aus.
. Wählen Sie den Wiederherstellungstyp aus:
+
** *Wiederherstellen auf ursprünglichen Namespaces*: Verwenden Sie dieses Verfahren, um die App an Ort und Stelle auf dem ursprünglichen Cluster wiederherzustellen.
+
... Wählen Sie den Snapshot oder das Backup aus, mit dem die App direkt wiederhergestellt werden soll. Dadurch wird die App auf eine frühere Version von selbst zurückgesetzt.
... Wählen Sie *Weiter*.
+

NOTE: Wenn Sie in einem zuvor gelöschten Namespace wiederherstellen, wird im Rahmen des Wiederherstellungsprozesses ein neuer Namespace mit demselben Namen erstellt. Alle Benutzer, die über Berechtigungen zum Verwalten von Apps im zuvor gelöschten Namespace verfügen, müssen die Rechte für den neu erstellten Namespace manuell wiederherstellen.



** *Wiederherstellen auf neuen Namespaces*: Verwenden Sie dieses Verfahren, um die App auf einem anderen Cluster oder mit verschiedenen Namespaces von der Quelle wiederherzustellen. Mit diesem Verfahren können Sie auch eine App zu einer anderen Storage-Klasse migrieren.
+
... Geben Sie den Namen für die wiederhergestellte App an.
... Wählen Sie das Ziel-Cluster für die Anwendung aus, die Sie wiederherstellen möchten.
... Geben Sie für jeden mit der App verknüpften Quell-Namespace einen Ziel-Namespace ein.
+

NOTE: Astra Control erstellt als Teil dieser Wiederherstellungsoption neue Ziel-Namespaces. Die angegebenen Ziel-Namespaces dürfen nicht bereits im Ziel-Cluster vorhanden sein.

... Wählen Sie *Weiter*.
... Wählen Sie den Snapshot oder das Backup aus, mit dem die App wiederhergestellt werden soll.
... Wählen Sie *Weiter*.
... Folgenden Optionen wählbar:
+
**** *Wiederherstellung unter Verwendung der ursprünglichen Speicherklassen*: Die Anwendung verwendet die ursprünglich zugeordnete Speicherklasse, es sei denn, sie existiert nicht auf dem Zielcluster. In diesem Fall wird die Standard-Storage-Klasse für das Cluster verwendet.
**** *Wiederherstellen mit einer anderen Storage-Klasse*: Wählen Sie eine Storage-Klasse aus, die auf dem Ziel-Cluster vorhanden ist. Alle Applikations-Volumes, unabhängig von den ursprünglich zugewiesenen Storage-Klassen, werden im Rahmen der Wiederherstellung in diese andere Storage-Klasse migriert.


... Wählen Sie *Weiter*.




. Wählen Sie die Ressourcen aus, die gefiltert werden sollen:
+
** *Alle Ressourcen wiederherstellen*: Alle mit der ursprünglichen App verknüpften Ressourcen wiederherstellen.
** *Ressourcen filtern*: Geben Sie Regeln an, um einen Untersatz der ursprünglichen Anwendungsressourcen wiederherzustellen:
+
... Wählen Sie diese Option, um Ressourcen aus der wiederhergestellten Anwendung einzuschließen oder auszuschließen.
... Wählen Sie entweder *Include rule* oder *Add exclude rule* aus und konfigurieren Sie die Regel, um die richtigen Ressourcen während der Anwendungswiederherstellung zu filtern. Sie können eine Regel bearbeiten oder entfernen und eine Regel erneut erstellen, bis die Konfiguration korrekt ist.
+

NOTE: Weitere Informationen zum Konfigurieren von Einschließen- und Ausschlussregeln finden Sie unter <<Filtern Sie Ressourcen während einer Anwendungswiederherstellung>>.





. Wählen Sie *Weiter*.
. Lesen Sie die Details zur Wiederherstellungsaktion sorgfältig durch, geben Sie „Restore“ ein (falls Sie dazu aufgefordert werden), und wählen Sie *Restore*.




== [Tech Preview] Wiederherstellen von Backups mithilfe einer benutzerdefinierten Ressource (CR)

Sie können Daten aus einem Backup mithilfe einer benutzerdefinierten Ressourcendatei (CR) entweder in einem anderen Namespace oder im ursprünglichen QuellNamespace wiederherstellen.

[role="tabbed-block"]
====
.Mit einem CR-System aus der Sicherung wiederherstellen
--
.Schritte
. Erstellen Sie die CR-Datei (Custom Resource) und benennen Sie sie `astra-control-backup-restore-cr.yaml`. Aktualisieren Sie die Werte in Klammern <>, um sie an die Astra Control-Umgebung und die Cluster-Konfiguration anzupassen:
+
** <CR_NAME>: Der Name dieser CR-Operation; wählen Sie einen vernünftigen Namen für Ihre Umgebung.
** <APPVAULT_NAME>: Der Name des AppVault, in dem der Backup-Inhalt gespeichert ist.
** <BACKUP_PATH>: Der Pfad innerhalb von AppVault, wo die Backup-Inhalte gespeichert werden. Beispiel:
+
[listing]
----
ONTAP-S3_1343ff5e-4c41-46b5-af00/backups/schedule-20231213023800_94347756-9d9b-401d-a0c3
----
** <SOURCE_NAMESPACE>: Der Quell-Namespace des Wiederherstellungsvorgangs.
** <DESTINATION_NAMESPACE>: Der Ziel-Namespace des Wiederherstellungsvorgangs.
+
[source, yaml]
----
apiVersion: astra.netapp.io/v1
kind: BackupRestore
metadata:
  name: <CR_NAME>
  namespace: astra-connector
spec:
  appVaultRef: <APPVAULT_NAME>
  appArchivePath: <BACKUP_PATH>
  namespaceMapping: [{"source": "<SOURCE_NAMESPACE>", "destination": "<DESTINATION_NAMESPACE>"}]
----




Ungelöste Direktive in <stdin> - include:../_include/selective-Restore-cr.adoc[]

. Nachdem Sie das ausgefüllt haben `astra-control-backup-restore-cr.yaml` Datei mit den richtigen Werten, CR anwenden:
+
[source, console]
----
kubectl apply -f astra-control-backup-restore-cr.yaml
----


--
.Wiederherstellung aus dem Backup in den ursprünglichen Namespace mit einem CR
--
.Schritte
. Erstellen Sie die CR-Datei (Custom Resource) und benennen Sie sie `astra-control-backup-ipr-cr.yaml`. Aktualisieren Sie die Werte in Klammern <>, um sie an die Astra Control-Umgebung und die Cluster-Konfiguration anzupassen:
+
** <CR_NAME>: Der Name dieser CR-Operation; wählen Sie einen vernünftigen Namen für Ihre Umgebung.
** <APPVAULT_NAME>: Der Name des AppVault, in dem der Backup-Inhalt gespeichert ist.
** <BACKUP_PATH>: Der Pfad innerhalb von AppVault, wo die Backup-Inhalte gespeichert werden. Beispiel:
+
[listing]
----
ONTAP-S3_1343ff5e-4c41-46b5-af00/backups/schedule-20231213023800_94347756-9d9b-401d-a0c3
----
+
[source, yaml]
----
apiVersion: astra.netapp.io/v1
kind: BackupInplaceRestore
metadata:
  name: <CR_NAME>
  namespace: astra-connector
spec:
  appVaultRef: <APPVAULT_NAME>
  appArchivePath: <BACKUP_PATH>
----




Ungelöste Direktive in <stdin> - include:../_include/selective-Restore-cr.adoc[]

. Nachdem Sie das ausgefüllt haben `astra-control-backup-ipr-cr.yaml` Datei mit den richtigen Werten, CR anwenden:
+
[source, console]
----
kubectl apply -f astra-control-backup-ipr-cr.yaml
----


--
====


== [Tech Preview] Wiederherstellen von Snapshots mithilfe einer benutzerdefinierten Ressource (CR)

Sie können Daten aus einem Snapshot mithilfe einer benutzerdefinierten Ressourcendatei (CR) entweder in einem anderen Namespace oder im ursprünglichen QuellNamespace wiederherstellen.

[role="tabbed-block"]
====
.Mit einem CR-System aus Snapshot wiederherstellen
--
.Schritte
. Erstellen Sie die CR-Datei (Custom Resource) und benennen Sie sie `astra-control-snapshot-restore-cr.yaml`. Aktualisieren Sie die Werte in Klammern <>, um sie an die Astra Control-Umgebung und die Cluster-Konfiguration anzupassen:
+
** <CR_NAME>: Der Name dieser CR-Operation; wählen Sie einen vernünftigen Namen für Ihre Umgebung.
** <APPVAULT_NAME>: Der Name des AppVault, in dem der Backup-Inhalt gespeichert ist.
** <BACKUP_PATH>: Der Pfad innerhalb von AppVault, wo die Backup-Inhalte gespeichert werden. Beispiel:
+
[listing]
----
ONTAP-S3_1343ff5e-4c41-46b5-af00/backups/schedule-20231213023800_94347756-9d9b-401d-a0c3
----
** <SOURCE_NAMESPACE>: Der Quell-Namespace des Wiederherstellungsvorgangs.
** <DESTINATION_NAMESPACE>: Der Ziel-Namespace des Wiederherstellungsvorgangs.
+
[source, yaml]
----
apiVersion: astra.netapp.io/v1
kind: SnapshotRestore
metadata:
  name: <CR_NAME>
  namespace: astra-connector
spec:
  appArchivePath: <BACKUP_PATH>
  appVaultRef: <APPVAULT_NAME>
  namespaceMapping: [{"source": "<SOURCE_NAMESPACE>", "destination": "<DESTINATION_NAMESPACE>"}]
----




Ungelöste Direktive in <stdin> - include:../_include/selective-Restore-cr.adoc[]

. Nachdem Sie das ausgefüllt haben `astra-control-snapshot-restore-cr.yaml` Datei mit den richtigen Werten, CR anwenden:
+
[source, console]
----
kubectl apply -f astra-control-snapshot-restore-cr.yaml
----


--
.Wiederherstellen von Snapshots in den ursprünglichen Namespace mit einem CR
--
.Schritte
. Erstellen Sie die CR-Datei (Custom Resource) und benennen Sie sie `astra-control-snapshot-ipr-cr.yaml`. Aktualisieren Sie die Werte in Klammern <>, um sie an die Astra Control-Umgebung und die Cluster-Konfiguration anzupassen:
+
** <CR_NAME>: Der Name dieser CR-Operation; wählen Sie einen vernünftigen Namen für Ihre Umgebung.
** <APPVAULT_NAME>: Der Name des AppVault, in dem der Backup-Inhalt gespeichert ist.
** <BACKUP_PATH>: Der Pfad innerhalb von AppVault, wo die Backup-Inhalte gespeichert werden. Beispiel:
+
[listing]
----
ONTAP-S3_1343ff5e-4c41-46b5-af00/backups/schedule-20231213023800_94347756-9d9b-401d-a0c3
----
+
[source, yaml]
----
apiVersion: astra.netapp.io/v1
kind: SnapshotInplaceRestore
metadata:
  name: <CR_NAME>
  namespace: astra-connector
spec:
  appArchivePath: <BACKUP_PATH>
  appVaultRef: <APPVAULT_NAME>
----




Ungelöste Direktive in <stdin> - include:../_include/selective-Restore-cr.adoc[]

. Nachdem Sie das ausgefüllt haben `astra-control-snapshot-ipr-cr.yaml` Datei mit den richtigen Werten, CR anwenden:
+
[source, console]
----
kubectl apply -f astra-control-snapshot-ipr-cr.yaml
----


--
====
.Ergebnis
Astra Control stellt die App basierend auf den von Ihnen angegebenen Informationen wieder her. Wenn Sie die Applikation bereits wiederhergestellt haben, wird der Inhalt vorhandener persistenter Volumes durch den Inhalt persistenter Volumes aus der wiederhergestellten App ersetzt.


NOTE: Nach einer Datensicherungsoperation (Klonen, Backup oder Wiederherstellung) und einer anschließenden Anpassung des persistenten Volumes beträgt die Verzögerung bis zu zwanzig Minuten, bevor die neue Volume-Größe in der Web-Benutzeroberfläche angezeigt wird. Der Datensicherungsvorgang ist innerhalb von Minuten erfolgreich und Sie können mit der Management Software für das Storage-Backend die Änderung der Volume-Größe bestätigen.


NOTE: Jeder Mitgliedsbenutzer mit Namespace-Einschränkungen nach Namespace-Name/ID oder anhand von Namespace-Bezeichnungen kann eine Applikation in einem neuen Namespace im selben Cluster oder einem anderen Cluster in seinem Unternehmenskonto klonen oder wiederherstellen. Derselbe Benutzer kann jedoch nicht auf die geklonte oder wiederhergestellte Anwendung im neuen Namespace zugreifen. Nachdem durch einen Klon- oder Wiederherstellungsvorgang ein neuer Namespace erstellt wurde, kann der Kontoadministrator/Kontoinhaber das Mitgliedskonto bearbeiten und Rolleneinschränkungen aktualisieren, damit der betroffene Benutzer Zugriff auf den neuen Namespace gewährt.



== Filtern Sie Ressourcen während einer Anwendungswiederherstellung

Sie können eine Filterregel zu einem hinzufügen link:../use/restore-apps.html["Wiederherstellen"] Vorgang, bei dem vorhandene Anwendungsressourcen angegeben werden, die in die wiederhergestellte Anwendung einbezogen oder von ihr ausgeschlossen werden sollen. Sie können Ressourcen basierend auf einem bestimmten Namespace, Label oder GVK (GroupVersionRind) ein- oder ausschließen.

.Lesen Sie mehr über ein- und Ausschlussszenarien
[%collapsible]
====
* *Sie wählen eine Include-Regel mit ursprünglichen Namespaces (in-Place-Wiederherstellung)*: Vorhandene Anwendungsressourcen, die Sie in der Regel definieren, werden gelöscht und durch jene aus dem ausgewählten Snapshot oder Backup ersetzt, den Sie für die Wiederherstellung verwenden. Alle Ressourcen, die Sie nicht in der Include-Regel angeben, bleiben unverändert.
* *Sie wählen eine Include-Regel mit neuen Namespaces*: Verwenden Sie die Regel, um die spezifischen Ressourcen auszuwählen, die Sie in der wiederhergestellten Anwendung benötigen. Alle Ressourcen, die Sie nicht in der Include-Regel angeben, werden nicht in die wiederhergestellte Anwendung aufgenommen.
* *Sie wählen eine Ausschlussregel mit ursprünglichen Namespaces (in-Place-Wiederherstellung)*: Die von Ihnen angegebenen Ressourcen werden nicht wiederhergestellt und bleiben unverändert. Ressourcen, die Sie nicht ausschließen möchten, werden vom Snapshot oder Backup wiederhergestellt. Alle Daten auf persistenten Volumes werden gelöscht und neu erstellt, wenn das entsprechende StatefulSet Teil der gefilterten Ressourcen ist.
* *Sie wählen eine Ausschlussregel mit neuen Namespaces* aus: Wählen Sie mit der Regel die Ressourcen aus, die Sie aus der wiederhergestellten Anwendung entfernen möchten. Ressourcen, die Sie nicht ausschließen möchten, werden vom Snapshot oder Backup wiederhergestellt.


====
Regeln sind entweder Einschließen oder Ausschließen von Typen. Regeln, die Ressourceneinschluss und -Ausschluss kombinieren, sind nicht verfügbar.

.Schritte
. Nachdem Sie die Option Ressourcen filtern und im Assistenten zum Wiederherstellen von Apps eine Option ein- oder ausschließen ausgewählt haben, wählen Sie *Einschlussregel hinzufügen* oder *Ausschlussregel hinzufügen* aus.
+

NOTE: Sie können keine im Cluster enthaltenen Ressourcen ausschließen, die von Astra Control automatisch berücksichtigt werden.

. Konfigurieren Sie die Filterregel:
+

NOTE: Sie müssen mindestens einen Namespace, eine Bezeichnung oder GVK angeben. Stellen Sie sicher, dass alle Ressourcen, die Sie behalten, nachdem die Filterregeln angewendet wurden, ausreichend sind, um die wiederhergestellte Anwendung in einem ordnungsgemäßen Zustand zu halten.

+
.. Wählen Sie einen bestimmten Namespace für die Regel aus. Wenn Sie keine Auswahl treffen, werden alle Namespaces im Filter verwendet.
+

NOTE: Wenn Ihre Anwendung ursprünglich mehrere Namespaces enthielt und Sie sie in neuen Namespaces wiederherstellen, werden alle Namespaces erstellt, auch wenn sie keine Ressourcen enthalten.

.. (Optional) Geben Sie einen Ressourcennamen ein.
.. (Optional) *Etikettenauswahl*: A einschließen https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors["Etikettenauswahl"^] Um der Regel hinzuzufügen. Mit der Etikettenauswahl werden nur die Ressourcen gefiltert, die der ausgewählten Bezeichnung entsprechen.
.. (Optional) Wählen Sie *Use GVK (GroupVersionRind) Set, um Ressourcen zu filtern*, um weitere Filteroptionen zu erhalten.
+

NOTE: Wenn Sie einen GVK-Filter verwenden, müssen Sie Version und Art angeben.

+
... (Optional) *Gruppe*: Wählen Sie aus der Dropdown-Liste die Kubernetes API-Gruppe aus.
... *Kind*: Wählen Sie aus der Dropdown-Liste das Objektschema für den Kubernetes-Ressourcentyp aus, der im Filter verwendet werden soll.
... *Version*: Wählen Sie die Kubernetes API Version.




. Überprüfen Sie die Regel, die auf Ihren Einträgen erstellt wird.
. Wählen Sie *Hinzufügen*.
+

TIP: Sie können beliebig viele Regeln für ein- und Ausschlussressourcen erstellen. Die Regeln werden in der Zusammenfassung der Wiederherstellungsanwendung angezeigt, bevor Sie den Vorgang starten.


