---
sidebar: sidebar 
permalink: use/set-up-billing.html 
keywords: billing, set up billing, payments, set up payments, credit card, update credit card, change credit card, free plan, free trial, premium, premium plan 
summary: Astra Control Service bietet Ihnen zwei Möglichkeiten zur Abrechnung Ihrer Namensvetter. Mit dem kostenlosen Plan können Sie bis zu 10 Apps in Ihrem Konto verwalten. Wenn Sie mehr als 10 Namespaces verwalten möchten, müssen Sie die Abrechnung durch ein Upgrade vom kostenlosen Plan auf den Premium-Plan einrichten. Alternativ können Sie auch über den Azure oder AWS Marketplace die Abrechnung für Azure oder AWS managen. 
---
= Abrechnung einrichten
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Sie können für die Verwaltung Ihrer Astra Control Service-Kontoabrechnung mehrere Methoden verwenden. Wenn Sie Azure oder Amazon AWS nutzen, können Sie einen Astra Control Service-Plan über den Microsoft Azure Marketplace oder AWS Marketplace abonnieren. Wenn Sie dies tun, können Sie Ihre Rechnungsdetails über den Marktplatz verwalten. Sie können sich auch direkt für NetApp anmelden. Wenn Sie sich direkt bei NetApp anmelden, können Sie über den Astra Control Service Ihre Rechnungsdetails verwalten. Wenn Sie den Astra Control Service ohne Abonnement nutzen, werden Sie automatisch beim Free Plan angemeldet.

Mit dem Astra Control Service Free Plan können Sie bis zu 10 Namespaces in Ihrem Konto verwalten. Wenn Sie mehr als 10 Namespaces verwalten möchten, müssen Sie Rechnungen einrichten. Dazu müssen Sie ein Upgrade vom Free Plan auf den Premium Plan durchführen oder den Azure Marketplace oder AWS Marketplace abonnieren.



== Übersicht über die Abrechnung

Mit dem Astra Control Service stehen zwei Kostenarten zur Verfügung: Die Kosten für den Astra Control Service fallen durch NetApp an. Die Kosten für persistenten Volumes und Objekt-Storage fallen vom Cloud-Provider an.



=== Fakturierung des Astra Control Service

Der Astra Control Service umfasst drei Pläne:

Kostenloser Plan:: Verwalten Sie bis zu 10 Namespaces kostenlos.
Premium-PAYGO:: Managen Sie eine unbegrenzte Anzahl von Namespaces zu einer bestimmten Rate pro Namespace.
Premium-Abonnement:: Mit einem Jahresabonnement, mit dem Sie bis zu 20 Namespaces pro _Namespace Pack_ verwalten können, können Sie vorab zu einem ermäßigten Preis zahlen. Wenden Sie sich an den NetApp Vertrieb, um so viele Pakete wie nötig zu erwerben. Erwerben Sie beispielsweise 3 Pakete, um 60 Namespaces über Astra Control Service zu managen. Wenn Sie mehr Namespaces verwalten als von Ihrem Jahresabonnement erlaubt, werden Ihnen die Abonnementgebühr für einen zusätzlichen Namespace berechnet. Wenn Sie noch kein Astra Control Konto haben, erstellt der Kauf des Premium Subscription automatisch ein Astra Control-Konto für Sie. Wenn Sie bereits einen kostenlosen Plan besitzen, werden Sie automatisch in das Premium-Abonnement konvertiert.


Wenn Sie ein Astra Control-Konto erstellen, sind Sie automatisch beim Free Plan angemeldet. Das Dashboard von Astra Control zeigt Ihnen, wie viele Namespaces Sie derzeit aus den 10 freien Namespaces verwalten, die Sie zugelassen haben. Die Abrechnung beginnt für einen Namespace, wenn die erste App, die den Namespace enthält, verwaltet wird und stoppt für diesen Namespace, wenn die letzte App, die den Namespace enthält, nicht verwaltet wird.

Wenn Sie versuchen, einen 11. Namespace zu verwalten, benachrichtigt Astra Control Sie, dass Sie die Grenze des Freiplans erreicht haben. Anschließend werden Sie aufgefordert, ein Upgrade vom kostenlosen Plan auf einen Premium-Plan durchzuführen. Sie erhalten die Gebühr für die abonnementabhängige Überalterrate pro zusätzlichem Namespace.

Sie können jederzeit ein Upgrade auf einen Premium Plan durchführen. Nach dem Upgrade beginnt Astra Control Sie mit dem Aufladen von _all_ Namespaces im Konto. Die ersten 10 Namensräume bleiben nicht im Free Plan.

ifdef::gcp[]



=== Google Cloud Rechnungen

Persistente Volumes werden durch NetApp Cloud Volumes Service gesichert und Backups von Applikationen werden in einem Google Cloud-Bucket gespeichert.

* https://cloud.google.com/solutions/partners/netapp-cloud-volumes/costs["Weitere Informationen zur Preisgestaltung für Cloud Volumes Service"^].
+
Beachten Sie, dass der Astra Control Service alle Servicetypen und Servicelevel unterstützt. Der von Ihnen verwendete Servicetyp hängt von Ihrem ab https://cloud.netapp.com/cloud-volumes-global-regions#cvsGcp["Google Cloud-Region"^].

* https://cloud.google.com/storage/pricing["Hier finden Sie Preisdetails für Google Cloud Storage Buckets"^].


endif::gcp[]

ifdef::azure[]



=== Microsoft Azure Abrechnung

Persistente Volumes werden durch Azure NetApp Files gesichert und Backups Ihrer Applikationen werden in einem Azure Blob-Container gespeichert.

* https://azure.microsoft.com/en-us/pricing/details/netapp["Weitere Informationen zur Preisgestaltung für Azure NetApp Files"^].
* https://azure.microsoft.com/en-us/pricing/details/storage/blobs["Sehen Sie sich Preisdetails für Microsoft Azure Blob Storage an"^].
* https://azuremarketplace.microsoft.com/en-us/marketplace/apps/netapp.netapp-astra-acs?tab=PlansAndPrice["Sehen Sie sich die Pläne und Preise für Astra Control Service im Azure Marketplace an"]



NOTE: Der Azure-Abrechnungssatz für den Astra Control Service gilt pro Stunde, nach Ablauf der 29 Minuten der Nutzungsstunde beginnt eine neue Abrechnungsstunde.

endif::azure[]

ifdef::aws[]



=== Amazon Web Services Abrechnung

Persistente Volumes werden durch EBS oder FSX for NetApp ONTAP gesichert und Backups Ihrer Applikationen werden in einem AWS-Bucket gespeichert.

* https://aws.amazon.com/eks/pricing/["Preisdetails zu Amazon Web Services anzeigen"^].


endif::aws[]



== Abonnieren Sie den Astra Control Service im Azure Marketplace

Astra Control Service können Sie über den Azure Marketplace abonnieren. Ihre Konto- und Rechnungsdaten werden über den Marketplace verwaltet.


NOTE: Eine Videoeingangsfunktion zum Abonnement von Azure Marketplace finden Sie unter https://media.netapp.com/video-detail/1bf9c3db-2b60-520d-bde6-b8996e7301f0/subscribing-to-the-astra-control-service-from-microsoft-azure-marketplace["NetApp TV"^].

.Schritte
. Wechseln Sie zum https://azuremarketplace.microsoft.com/en-us/marketplace/apps/netapp.netapp-astra-acs?tab=Overview["Azure Marketplace"^].
. Wählen Sie *Jetzt Holen*.
. Befolgen Sie die Anweisungen, um einen Plan zu abonnieren.




== Abonnieren Sie den Astra Control Service im AWS Marketplace

Sie können den Astra Control Service über den AWS Marketplace abonnieren. Ihre Konto- und Rechnungsdaten werden über den Marketplace verwaltet.

.Schritte
. Wechseln Sie zum https://aws.amazon.com/marketplace/pp/prodview-auupmqjoq43ey?sr=0-1&ref_=beagle&applicationId=AWSMPContessa["AWS Marketplace"^].
. Wählen Sie *Kaufoptionen anzeigen*.
. Wenn Sie dazu aufgefordert werden, melden Sie sich bei Ihrem AWS-Konto an, oder erstellen Sie ein neues Konto.
. Befolgen Sie die Anweisungen, um einen Plan zu abonnieren.




== Abonnieren Sie den Astra Control Service direkt mit NetApp

Sie können den Astra Control Service über die Astra Control Service UI abonnieren oder sich an den NetApp Sales wenden.



=== Upgrade vom kostenlosen Plan auf den Premium PAYGO Plan

Aktualisieren Sie Ihren Rechnungsplan jederzeit, um mehr als 10 Namespaces von Astra Control zu verwalten, indem Sie bezahlen, wie Sie gehen. Sie brauchen nur eine gültige Kreditkarte.

.Schritte
. Wählen Sie *Konto* und dann *Abrechnung*.
. Gehen Sie unter *Pläne* zu *Premium PAYGO* und wählen Sie *Upgrade Now*.
. Geben Sie Zahlungsdetails für eine gültige Kreditkarte an und wählen Sie *Upgrade auf Premium Plan*.
+

NOTE: Astra Control sendet Ihnen eine E-Mail, wenn sich die Kreditkarte dem Ablauf nähert.



.Ergebnis
Sie können jetzt mehr als 10 Namespaces verwalten. Astra Control lädt Sie für alle Namespaces, die Sie derzeit verwalten.



=== Upgrade vom kostenlosen Plan auf das Premium-Abonnement

Wenden Sie sich an NetApp Sales, um im Rahmen eines Jahresabonnements eine Vorlaufzeit zu einem reduzierten Preis zu erhalten.

.Schritte
. Wählen Sie *Konto* und dann *Abrechnung*.
. Gehen Sie unter *Pläne* zu *Premium-Abonnement* und wählen Sie *Vertrieb kontaktieren*.
. Geben Sie dem Vertriebsteam Details an, um den Prozess zu starten.


.Ergebnis
Ein NetApp Vertriebsmitarbeiter wird sich mit Ihnen in Verbindung setzen, um Ihre Bestellung zu bearbeiten. Nachdem die Bestellung abgeschlossen ist, wird Astra Control Ihren aktuellen Plan auf der Registerkarte *Abrechnung* widerspiegeln.



== Zeigt den aktuellen Kosten- und Abrechnungsverlauf an

Astra Control zeigt Ihnen Ihre aktuellen monatlichen Kosten sowie einen detaillierten Abrechnungsverlauf per Namespace. Wenn Sie einen Plan über einen Marktplatz abonniert haben, ist der Rechnungsverlauf nicht sichtbar (Sie können ihn aber anzeigen, indem Sie sich am Marktplatz anmelden.)

.Schritte
. Wählen Sie *Konto* und dann *Abrechnung*.
+
Ihre aktuellen Kosten werden in der Übersicht über die Abrechnung angezeigt.

. Um den Abrechnungsverlauf nach Namespace anzuzeigen, wählen Sie *Abrechnungsverlauf* aus.
+
Astra Control zeigt Ihnen die Nutzungsminuten und die Kosten für jeden Namespace. Eine Nutzungsminute ist, wie viele Minuten Astra Control Ihren Namespace in einem Abrechnungszeitraum verwaltet hat.

. Wählen Sie die Dropdown-Liste aus, um einen vorherigen Monat auszuwählen.




== Ändern Sie die Kreditkarte für Premium PAYGO

Bei Bedarf können Sie die Kreditkarte, die Astra Control zur Abrechnung hat, ändern.

.Schritte
. Wählen Sie *Konto > Abrechnung > Zahlungsart*.
. Wählen Sie das Symbol Konfigurieren.
. Ändern Sie die Kreditkarte.




== Wichtige Hinweise

* Ihr Rechnungsplan ist per Astra Control Konto.
+
Wenn Sie mehrere Konten haben, hat jeder seinen eigenen Abrechnungsplan.

* Ihre Astra Control-Rechnung enthält Gebühren für die Verwaltung Ihrer Namespaces. Für das Storage-Back-End für persistente Volumes werden Sie von Ihrem Cloud-Provider separat berechnet.
+
link:../get-started/intro.html["Erfahren Sie mehr über die Astra Control-Preise"].

* Jeder Abrechnungszeitraum endet am letzten Tag des Monats.
* Sie können nicht von einem Premium-Plan auf den kostenlosen Plan herunterstufen.

