---
sidebar: sidebar 
permalink: use/view-apps.html 
keywords: view app, view app status, view app protection status, view app pods, view persistent storage 
summary: Nachdem Sie mit dem Management einer Applikation begonnen haben, stellt Astra Control Details zur Applikation bereit, mit der Sie den Status, den Sicherungsstatus, die Pods, den persistenten Storage und viele andere mehr ermitteln können. 
---
= Anzeigen des Funktionszustands und der Details einer App
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Astra Control bietet nach dem Management einer App Details zu der App, mit der Sie den Kommunikationsstatus (ob Astra Control mit der App kommunizieren kann), den Sicherungsstatus (unabhängig davon, ob die App bei Ausfällen vollständig geschützt ist), die Pods, persistenten Storage usw. ermitteln können.

.Schritte
. Wählen Sie *Anwendungen* und dann den Namen einer App aus.
. Hier finden Sie die gewünschten Informationen:
+
Anwendungsstatus:: Zeigt einen Status an, der angibt, ob Astra Control mit der Applikation kommunizieren kann.
App-Schutzstatus:: Gibt den Status an, wie gut die App geschützt ist:
+
--
** *Vollständig geschützt*: Die App verfügt über einen aktiven Backup-Zeitplan und ein erfolgreiches Backup, das weniger als eine Woche alt ist
** *Teilweise geschützt*: Die App verfügt über einen aktiven Backup-Zeitplan, einen aktiven Snapshot-Zeitplan oder einen erfolgreichen Backup oder Snapshot
** *Ungeschützt*: Apps, die weder vollständig geschützt noch teilweise geschützt sind.
+
_Sie können erst dann vollständig geschützt sein, wenn Sie ein kürzlich gesichertes Backup haben. Das ist wichtig, da Backups abseits der persistenten Volumes in einem Objektspeicher gespeichert werden. Wenn ein Ausfall das Cluster herauswischt und es sich um den persistenten Storage handelt, muss das Backup wiederhergestellt werden. Ein Snapshot würde es Ihnen nicht ermöglichen, eine Wiederherstellung durchzuführen.



--
Überblick:: Informationen über den Status der Pods, die mit der App verknüpft sind.
Datensicherung:: Hiermit können Sie eine Datenschutzrichtlinie konfigurieren und die vorhandenen Snapshots und Backups anzeigen.
Storage:: Zeigt Ihnen die persistenten Volumes auf App-Ebene. Der Zustand eines persistenten Volumes befindet sich aus der Perspektive des Kubernetes Clusters.
Ressourcen:: Hiermit können Sie überprüfen, welche Ressourcen gesichert und gemanagt werden.
Aktivität:: Die Astra Control Aktivitäten im Zusammenhang mit der App.



