---
sidebar: sidebar 
permalink: get-started/add-private-provider-managed-cluster.html 
keywords: discover cluster, add cluster, add kubernetes cluster, discover kubernetes cluster, add cluster 
summary: Nach der Einrichtung der Umgebung erstellen Sie sofort einen Kubernetes Cluster und fügen ihn dann dem Astra Control Service hinzu. 
---
= Fügen Sie dem Astra Control Service einen über privaten Provider gemanagten Cluster hinzu
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Mit Astra Control Service können Sie private GKE-Cluster (Google Kubernetes Engine) managen. In diesen Anweisungen wird davon ausgegangen, dass Sie bereits einen privaten AKS- oder OpenShift-Cluster erstellt und eine sichere Methode für den Remote-Zugriff darauf vorbereitet haben. Weitere Informationen zum Erstellen und Zugreifen auf private AKS- oder OpenShift-Cluster finden Sie in der folgenden Dokumentation:

* https://docs.microsoft.com/azure/aks/private-clusters["Azure-Dokumentation für private AKS-Cluster"^]
* https://learn.microsoft.com/en-us/azure/openshift/howto-create-private-cluster-4x["Azure-Dokumentation für private OpenShift-Cluster"^]


Mit Astra Control Service können Sie private Azure Kubernetes Service (AKS)-Cluster sowie private Red hat OpenShift-Cluster in AKS managen. In diesen Anweisungen wird davon ausgegangen, dass Sie bereits einen privaten AKS- oder OpenShift-Cluster erstellt und eine sichere Methode für den Remote-Zugriff darauf vorbereitet haben. Weitere Informationen zum Erstellen und Zugreifen auf private AKS- oder OpenShift-Cluster finden Sie in der folgenden Dokumentation:

* https://docs.microsoft.com/azure/aks/private-clusters["Azure-Dokumentation für private AKS-Cluster"^]
* https://learn.microsoft.com/en-us/azure/openshift/howto-create-private-cluster-4x["Azure-Dokumentation für private OpenShift-Cluster"^]


Mit Astra Control Service können Sie private EKS-Cluster (Amazon Elastic Kubernetes Service) managen. In diesen Anweisungen wird davon ausgegangen, dass Sie bereits einen privaten EKS-Cluster erstellt und eine sichere Methode für den Remote-Zugriff darauf vorbereitet haben. Weitere Informationen zum Erstellen und Zugreifen auf private EKS-Cluster finden Sie im https://docs.aws.amazon.com/eks/latest/userguide/private-clusters.html["Amazon EKS-Dokumentation"^].

Führen Sie die folgenden Aufgaben aus, um Ihren privaten Cluster zum Astra Control Service hinzuzufügen:

. <<Astra Connector Installieren>>
. <<Einrichtung von persistentem Storage>>
. <<Fügen Sie den über den privaten Provider gemanagten Cluster zu Astra Control Service hinzu>>




== Astra Connector Installieren

Bevor Sie einen privaten Cluster hinzufügen, müssen Sie Astra Connector im Cluster installieren, damit Astra Control damit kommunizieren kann. Siehe link:install-astra-connector.html["Astra Connector für private Cluster installieren"] Weitere Anweisungen.



== Einrichtung von persistentem Storage

Konfigurieren Sie persistenten Storage für das Cluster. In der Dokumentation „erste Schritte“ finden Sie weitere Informationen zum Konfigurieren von persistentem Storage:

ifdef::azure[]

* link:set-up-microsoft-azure-with-anf.html["Microsoft Azure mit Azure NetApp Files einrichten"^]
* link:set-up-microsoft-azure-with-amd.html["Richten Sie Microsoft Azure mit von Azure gemanagten Festplatten ein"^]


endif::azure[]

ifdef::aws[]

* link:set-up-amazon-web-services.html["Einrichten von Amazon Web Services"^]


endif::aws[]

ifdef::gcp[]

* link:set-up-google-cloud.html["Google Cloud einrichten"^]


endif::gcp[]



== Fügen Sie den über den privaten Provider gemanagten Cluster zu Astra Control Service hinzu

Sie können den privaten Cluster jetzt dem Astra Control Service hinzufügen.

Beachten Sie beim Management von Azure Kubernetes Service und Google Kubernetes Engine-Clustern, dass für die Installation von Astra Control und das Lifecycle Management zwei Optionen zur Verfügung stehen:

* Mit Astra Control Service können Sie den Lebenszyklus von Astra Control Provisioner automatisch managen. Vergewissern Sie sich dazu, dass Astra Trident nicht installiert ist und Astra Control Provisioner nicht auf dem Cluster aktiviert ist, den Sie mit Astra Control Service managen möchten. In diesem Fall aktiviert Astra Control Service automatisch die Astra Control-Bereitstellung, wenn Sie mit dem Cluster-Management beginnen. Upgrades für die Astra Control-Bereitstellung werden automatisch durchgeführt.
* Sie können den Lebenszyklus der Astra Control Provisionierung selbst managen. Aktivieren Sie hierfür die Astra Control-Provisionierung im Cluster, bevor Sie das Cluster mit Astra Control Service verwalten. In diesem Fall erkennt Astra Control Service, dass die Provisionierung von Astra Control bereits aktiviert ist. Es wird weder neu installiert noch Astra Control Provisioner-Upgrades gemanagt. Siehe link:../use/enable-acp.html["Astra Control Provisioner Aktivieren"^] Für die Schritte aktivieren Sie die Astra Control-Provisionierung.


Wenn Sie Amazon Web Services Cluster mit Astra Control Service managen, müssen Sie bei Bedarf Storage-Back-Ends, die nur mit dem Astra Control Provisioner verwendet werden können, die Astra Control Service manuell im Cluster aktivieren, bevor Sie die Bereitstellung mit Astra Control Service managen. Siehe link:../use/enable-acp.html["Astra Control Provisioner Aktivieren"^] Enthält die Schritte zum Aktivieren der Astra Control-Bereitstellung.

.Bevor Sie beginnen
[%collapsible%open]
====
ifdef::aws[]

.Amazon Web Services
* Sie sollten die JSON-Datei mit den Anmeldedaten des IAM-Benutzers haben, der das Cluster erstellt hat. link:../get-started/set-up-amazon-web-services.html#create-an-iam-user["Erfahren Sie, wie ein IAM-Benutzer erstellt wird"].
* Astra Control Provisioner ist für Amazon FSX for NetApp ONTAP erforderlich. Wenn Sie Amazon FSX for NetApp ONTAP als Storage-Backend für Ihr EKS-Cluster verwenden möchten, finden Sie in den Informationen zur Astra Control-Bereitstellung im link:set-up-amazon-web-services.html#eks-cluster-requirements["EKS-Clusteranforderungen"].
* (Optional) Wenn Sie angeben müssen `kubectl` Befehlszugriff für ein Cluster auf andere IAM-Benutzer, die nicht der Ersteller des Clusters sind, finden Sie in den Anweisungen unter https://aws.amazon.com/premiumsupport/knowledge-center/amazon-eks-cluster-access/["Wie erhalte ich Zugriff auf andere IAM-Benutzer und Rollen nach der Cluster-Erstellung in Amazon EKS?"^].
* Wenn Sie NetApp Cloud Volumes ONTAP als Storage-Backend verwenden möchten, müssen Sie Cloud Volumes ONTAP für die Nutzung mit Amazon Web Services konfigurieren. Weitere Informationen finden Sie im Cloud Volumes ONTAP https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-aws.html["Setup-Dokumentation"^].


endif::aws[]

ifdef::azure[]

.Microsoft Azure
* Sie sollten beim Erstellen des Service-Principal die JSON-Datei haben, die die Ausgabe aus der Azure CLI enthält. link:../get-started/set-up-microsoft-azure-with-anf.html#create-an-azure-service-principal-2["Erfahren Sie, wie Sie einen Service-Principal einrichten"].
+
Außerdem benötigen Sie Ihre Azure Abonnement-ID, wenn Sie sie nicht zur JSON-Datei hinzugefügt haben.



* Wenn Sie NetApp Cloud Volumes ONTAP als Storage-Backend verwenden möchten, müssen Sie Cloud Volumes ONTAP für die Zusammenarbeit mit Microsoft Azure konfigurieren. Weitere Informationen finden Sie im Cloud Volumes ONTAP https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-azure.html["Setup-Dokumentation"^].


endif::azure[]

ifdef::gcp[]

.Google Cloud
* Sie sollten die Servicekontoschlüsseldatei für ein Servicekonto haben, das über die erforderlichen Berechtigungen verfügt. link:../get-started/set-up-google-cloud.html#create-a-service-account["Erfahren Sie, wie Sie ein Service-Konto einrichten"].
* Wenn das Cluster privat ist, gilt das https://cloud.google.com/kubernetes-engine/docs/concepts/private-cluster-concept["Autorisierte Netzwerke"^] Die Astra Control Service-IP-Adresse muss zugelassen werden:
+
52.188.218.166/32

* Wenn Sie NetApp Cloud Volumes ONTAP als Storage-Backend verwenden möchten, müssen Sie Cloud Volumes ONTAP für die Zusammenarbeit mit Google Cloud konfigurieren. Weitere Informationen finden Sie im Cloud Volumes ONTAP https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-gcp.html["Setup-Dokumentation"^].


endif::gcp[]

====
.Schritte
. (Optional) Wenn Sie einen Amazon EKS Cluster hinzufügen oder die Installation und Upgrades von Astra Control Provisioner selbst managen möchten, aktivieren Sie die Astra Control Provisioner-Funktion im Cluster. Siehe link:../use/enable-acp.html["Astra Control Provisioner Aktivieren"^] Für Enablement-Schritte.
. Öffnen Sie die Web-UI des Astra Control Service in einem Browser.
. Wählen Sie im Dashboard *Kubernetes Cluster managen* aus.
+
Befolgen Sie die Aufforderungen zum Hinzufügen des Clusters.

. *Provider*: Wählen Sie Ihren Cloud-Provider aus und geben Sie dann entweder die erforderlichen Anmeldedaten für die Erstellung einer neuen Cloud-Instanz an, oder wählen Sie eine vorhandene Cloud-Instanz aus.


ifdef::aws[]

. *Amazon Web Services*: Geben Sie Details über Ihr Amazon Web Services IAM-Benutzerkonto an, indem Sie eine JSON-Datei hochladen oder den Inhalt dieser JSON-Datei aus Ihrer Zwischenablage einfügen.
+
Die JSON-Datei sollte die Anmeldeinformationen des IAM-Benutzers enthalten, der das Cluster erstellt hat.



endif::aws[]

ifdef::azure[]

. *Microsoft Azure*: Geben Sie Details zu Ihrem Azure Service Principal an, indem Sie eine JSON-Datei hochladen oder den Inhalt dieser JSON-Datei aus Ihrer Zwischenablage einfügen.
+
Die JSON-Datei sollte beim Erstellen des Service-Principal die Ausgabe aus der Azure CLI enthalten. Sie können auch Ihre Abonnement-ID angeben, damit sie automatisch in den Astra aufgenommen wird. Andernfalls müssen Sie die ID manuell eingeben, nachdem Sie den JSON bereitgestellt haben.



endif::azure[]

ifdef::gcp[]

. *Google Cloud Platform*: Stellen Sie die Service-Konto-Schlüsseldatei entweder durch das Hochladen der Datei oder durch Einfügen der Inhalte aus Ihrer Zwischenablage bereit.
+
Astra Control Service nutzt das Service-Konto, um Cluster zu erkennen, die in der Google Kubernetes Engine ausgeführt werden.



endif::gcp[]

. *Andere*: Diese Registerkarte ist nur für die Verwendung mit selbst verwalteten Clustern vorgesehen.
+
.. *Cloud-Instanzname*: Geben Sie einen Namen für die neue Cloud-Instanz an, die beim Hinzufügen dieses Clusters erstellt wird. Weitere Informationen zu link:../use/manage-cloud-instances.html["Cloud-Instanzen"].
.. Wählen Sie *Weiter*.
+
Astra Control Service zeigt eine Liste von Clustern an, aus denen Sie auswählen können.

.. *Cluster*: Wählen Sie einen Cluster aus der Liste aus, der zu Astra Control Service hinzugefügt werden soll.
+

NOTE: Wenn Sie aus der Liste der Cluster auswählen, achten Sie auf die Spalte *Eligiblity*. Wenn ein Cluster „nicht berechtigt“ oder „teilweise berechtigt“ ist, bewegen Sie den Mauszeiger über den Status, um zu ermitteln, ob ein Problem im Cluster vorliegt. Beispielsweise kann sie erkennen, dass für das Cluster kein Worker Node vorhanden ist.





. Wählen Sie *Weiter*.
. (Optional) *Speicher*: Wählen Sie optional die Storage-Klasse aus, die Kubernetes-Anwendungen, die auf diesem Cluster bereitgestellt werden sollen, standardmäßig verwenden sollen.
+
.. Um eine neue Standard-Storage-Klasse für den Cluster auszuwählen, aktivieren Sie das Kontrollkästchen *Neue Standard-Storage-Klasse zuweisen*.
.. Wählen Sie eine neue Standard-Storage-Klasse aus der Liste aus.
+
[NOTE]
====
Jeder Storage-Service eines Cloud-Providers enthält die folgenden Informationen zu Preis, Performance und Ausfallsicherheit:

ifdef::gcp[]

*** Cloud Volumes Service für Google Cloud: Informationen zu Preis, Performance und Ausfallsicherheit
*** Google Persistent Disk: Keine Informationen über Preis, Performance oder Ausfallsicherheit verfügbar


endif::gcp[]

ifdef::azure[]

*** Azure NetApp Files: Informationen zu Performance und Ausfallsicherheit
*** Azure Managed Disks: Es sind weder Preis-, Performance- oder Resilience-Informationen verfügbar


endif::azure[]

ifdef::aws[]

*** Amazon Elastic Block Store: Keine Informationen zu Preis, Performance oder Ausfallsicherheit verfügbar
*** Amazon FSX für NetApp ONTAP: Keine Informationen zu Preis, Performance und Ausfallsicherheit verfügbar


endif::aws[]

*** NetApp Cloud Volumes ONTAP: Keine Informationen zu Preis, Performance oder Ausfallsicherheit verfügbar


====
+
Jede Storage-Klasse kann einen der folgenden Services nutzen:





ifdef::gcp[]

* https://cloud.netapp.com/cloud-volumes-service-for-gcp["Cloud Volumes Service für Google Cloud"^]
* https://cloud.google.com/persistent-disk/["Google Persistent Disk"^]


endif::gcp[]

ifdef::azure[]

* https://cloud.netapp.com/azure-netapp-files["Azure NetApp Dateien"^]
* https://docs.microsoft.com/en-us/azure/virtual-machines/managed-disks-overview["Von Azure gemanagte Festplatten"^]


endif::azure[]

ifdef::aws[]

* https://docs.aws.amazon.com/ebs/["Amazon Elastic Block Store"^]
* https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX für NetApp ONTAP"^]


endif::aws[]

* https://www.netapp.com/cloud-services/cloud-volumes-ontap/what-is-cloud-volumes/["NetApp Cloud Volumes ONTAP"^]
+
Weitere Informationen zu link:../learn/aws-storage.html["Storage-Klassen für Amazon Web Services Cluster"]. Weitere Informationen zu link:../learn/azure-storage.html["Speicherklassen für AKS-Cluster"]. Weitere Informationen zu link:../learn/choose-class-and-size.html["Speicherklassen für GKE-Cluster"].

+
.. Wählen Sie *Weiter*.
.. *Überprüfen und genehmigen*: Überprüfen Sie die Konfigurationsdetails.
.. Wählen Sie *Add*, um den Cluster zu Astra Control Service hinzuzufügen.




.Ergebnis
Wenn dies der erste Cluster ist, den Sie für diesen Cloud-Provider hinzugefügt haben, erstellt Astra Control Service einen Objektspeicher für den Cloud-Provider für Backups von Anwendungen, die auf geeigneten Clustern ausgeführt werden. (Wenn Sie nachfolgende Cluster für diesen Cloud-Provider hinzufügen, werden keine weiteren Objektspeicher erstellt.) Wenn Sie eine Standard-Storage-Klasse angegeben haben, setzt Astra Control Service die von Ihnen angegebene Standard-Storage-Klasse ein. Für Cluster, die in Amazon Web Services oder Google Cloud Platform gemanagt werden, erstellt Astra Control Service auch ein Administratorkonto auf dem Cluster. Diese Vorgänge können mehrere Minuten dauern.



== Ändern der Standard-Storage-Klasse

Sie können die Standard-Storage-Klasse für ein Cluster ändern.



=== Ändern Sie die Standard-Storage-Klasse mit Astra Control

Sie können die Standard-Storage-Klasse für ein Cluster aus Astra Control ändern. Wenn Ihr Cluster einen zuvor installierten Speicher-Backend-Service verwendet, können Sie diese Methode möglicherweise nicht verwenden, um die Standard-Speicherklasse zu ändern (die Aktion *default* ist nicht wählbar). In diesem Fall können Sie <<Ändern Sie die Standard-Storage-Klasse über die Befehlszeile>>.

.Schritte
. Wählen Sie in der Astra Control Service-UI *Cluster* aus.
. Wählen Sie auf der Seite *Cluster* den Cluster aus, den Sie ändern möchten.
. Wählen Sie die Registerkarte *Storage* aus.
. Wählen Sie die Kategorie *Speicherklassen* aus.
. Wählen Sie das Menü *Aktionen* für die Speicherklasse aus, die Sie als Standard festlegen möchten.
. Wählen Sie *als Standard*.




=== Ändern Sie die Standard-Storage-Klasse über die Befehlszeile

Sie können die Standard-Storage-Klasse für ein Cluster mit Kubernetes-Befehlen ändern. Diese Methode funktioniert unabhängig von der Konfiguration Ihres Clusters.

.Schritte
. Melden Sie sich bei Ihrem Kubernetes Cluster an.
. Listen Sie die Storage-Klassen in Ihrem Cluster auf:
+
[source, console]
----
kubectl get storageclass
----
. Entfernen Sie die Standardbezeichnung aus der Standardspeicherklasse. Ersetzen Sie <SC_NAME> durch den Namen der Speicherklasse:
+
[source, console]
----
kubectl patch storageclass <SC_NAME> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
----
. Markieren Sie standardmäßig eine andere Storage-Klasse. Ersetzen Sie <SC_NAME> durch den Namen der Speicherklasse:
+
[source, console]
----
kubectl patch storageclass <SC_NAME> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
----
. Bestätigen Sie die neue Standard-Speicherklasse:
+
[source, console]
----
kubectl get storageclass
----


ifdef::azure[]
