---
sidebar: sidebar 
permalink: get-started/add-public-self-managed-cluster.html 
keywords: discover cluster, add cluster, add kubernetes cluster, discover kubernetes cluster, add cluster 
summary: Nach der Einrichtung der Umgebung erstellen Sie sofort einen Kubernetes Cluster und fügen ihn dann dem Astra Control Service hinzu. 
---
= Fügen Sie Astra Control Service einen öffentlichen, selbst gemanagten Cluster hinzu
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Nach der Einrichtung der Umgebung erstellen Sie sofort einen Kubernetes Cluster und fügen ihn dann dem Astra Control Service hinzu.

Ein selbstverwalteter Cluster ist ein Cluster, den Sie direkt bereitstellen und managen können. Astra Control Service unterstützt selbst gemanagte Cluster, die in einer Public-Cloud-Umgebung ausgeführt werden. Sie können einen selbstverwalteten Cluster zum Astra Control Service hinzufügen, indem Sie ein hochladen `kubeconfig.yaml` Datei: Sie müssen sicherstellen, dass das Cluster die hier aufgeführten Anforderungen erfüllt.



== Unterstützte Kubernetes-Distributionen

Mit Astra Control Service können Sie folgende Arten von öffentlichen, selbst gemanagten Clustern managen:

[cols="2*"]
|===
| Kubernetes-Distribution | Unterstützte Versionen 


| Kubernetes (Vorgelagert) | 1.27 bis 1.29 


| Rancher Kubernetes Engine (RKE) | RKE 1: Versionen 1.24.17, 1.25.13, 1.26.8 mit Rancher Manager 2.7.9
RKE 2: Versionen 1.23.16 und 1.24.13 mit Rancher Manager 2.6.13
RKE 2: Versionen 1.24.17, 1.25.14, 1.26.9 mit Rancher Manager 2.7.9 


| Red hat OpenShift Container Platform | 4.12 bis 4.14 
|===
Bei diesen Anweisungen wird davon ausgegangen, dass Sie bereits einen selbstverwalteten Cluster erstellt haben.

* <<Fügen Sie das Cluster zu Astra Control Service hinzu>>
* <<Ändern der Standard-Storage-Klasse>>




== Fügen Sie das Cluster zu Astra Control Service hinzu

Nachdem Sie sich beim Astra Control Service angemeldet haben, beginnen Sie zunächst mit dem Verwalten Ihrer Cluster. Bevor Sie Astra Control Service ein Cluster hinzufügen, müssen Sie bestimmte Aufgaben ausführen und sicherstellen, dass das Cluster bestimmte Anforderungen erfüllt.

.Bevor Sie beginnen
[%collapsible%open]
====
Ein selbstverwalteter Cluster ist ein Cluster, den Sie direkt bereitstellen und managen können. Astra Control Service unterstützt selbst gemanagte Cluster, die in einer Public-Cloud-Umgebung ausgeführt werden. Die selbstverwalteten Cluster können über Astra Control Provisioner eine Schnittstelle zu NetApp Storage-Services aufbauen. Alternativ können sie über CSI-Treiber (Container Storage Interface) eine Schnittstelle zu Amazon Elastic Block Store (EBS), Azure Managed Disks und Google Persistent Disk erstellen.

Astra Control Service unterstützt selbst gemanagte Cluster, die die folgenden Kubernetes-Distributionen verwenden:

* Red hat OpenShift Container Platform
* Rancher Kubernetes Engine
* Vorgelagerte Kubernetes-Systeme


Ihr Self-Managed-Cluster muss folgende Anforderungen erfüllen:

* Der Cluster muss über das Internet zugänglich sein.
* Wenn Sie Speicher mit CSI-Treibern verwenden oder planen, diese zu verwenden, müssen auf dem Cluster die entsprechenden CSI-Treiber installiert sein. Weitere Informationen zur Verwendung von CSI-Treibern zur Integration von Speicher finden Sie in der Dokumentation Ihres Speicherservices.
* Sie haben Zugriff auf die Cluster-Datei kubeconfig, die nur ein Kontextelement enthält. Folgen link:create-kubeconfig.html["Diese Anweisungen"^] Um eine kubeconfig-Datei zu erzeugen.
* Wenn Sie den Cluster mit einer kubeconfig-Datei hinzufügen, die auf eine private Zertifizierungsstelle verweist, fügen Sie der folgende Zeile hinzu `cluster` Abschnitt der Datei kubeconfig. So kann Astra Control das Cluster hinzufügen:
+
[listing]
----
insecure-skip-tls-verify: true
----
* *Rancher only*: Ändern Sie beim Verwalten von Anwendungsclustern in einer Rancher-Umgebung den Standardkontext des Anwendungsclusters in der von Rancher bereitgestellten kubeconfig-Datei, um einen Steuerebenen-Kontext anstelle des Rancher API-Serverkontexts zu verwenden. So wird die Last auf dem Rancher API Server reduziert und die Performance verbessert.
* *Anforderungen für die Astra Control-Bereitstellung*: Sie sollten einen ordnungsgemäß konfigurierten Astra Control Provisioner einschließlich der Astra Trident-Komponenten verwenden, um Cluster zu managen.
+
** *Umgebungsanforderungen für Astra Trident prüfen*: Lesen Sie vor der Installation oder dem Upgrade von Astra Control Provisioner die https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html["Unterstützte Frontends, Back-Ends und Host-Konfigurationen"^].
** *Astra Control-Provisioner aktivieren*: Es wird dringend empfohlen, Astra Trident 23.10 oder höher zu installieren und zu aktivieren link:../use/enable-acp.html["Astra Control bietet erweiterte Storage-Funktionen zur Bereitstellung"]. In den kommenden Versionen unterstützt Astra Control nicht Astra Trident, wenn der Astra Control Provisioner nicht ebenfalls aktiviert ist.
** *Konfiguration eines Speicher-Backends*: Mindestens ein Speicher-Backend muss sein https://docs.netapp.com/us-en/trident/trident-use/backends.html["In Astra Trident konfiguriert"^] Auf dem Cluster.
** *Konfiguration einer Storage-Klasse*: Mindestens eine Storage-Klasse muss sein https://docs.netapp.com/us-en/trident/trident-use/manage-stor-class.html["In Astra Trident konfiguriert"^] Auf dem Cluster. Wenn eine Standardspeicherklasse konfiguriert ist, stellen Sie sicher, dass sie die *einzige* Speicherklasse ist, die die Standardanmerkung hat.
** *Konfigurieren Sie einen Volume-Snapshot-Controller und installieren Sie eine Volume-Snapshot-Klasse*: https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html#deploy-a-volume-snapshot-controller["Installieren Sie einen Volume-Snapshot-Controller"] Damit Snapshots in Astra Control erstellt werden können. https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html#create-a-volume-snapshot["Erstellen"^] Mindestens eine `VolumeSnapshotClass` Einsatz von Astra Trident:




====
.Schritte
. Wählen Sie im Dashboard *Kubernetes Cluster managen* aus.
+
Befolgen Sie die Aufforderungen zum Hinzufügen des Clusters.

. *Provider*: Wählen Sie den Reiter *andere*, um Details zu Ihrem selbst verwalteten Cluster hinzuzufügen.
+
.. *Other*: Geben Sie Details über Ihren selbstverwalteten Cluster durch das Hochladen eines `kubeconfig.yaml` Datei oder durch Einfügen des Inhalts des `kubeconfig.yaml` Datei aus der Zwischenablage.
+

NOTE: Wenn Sie Ihre eigenen erstellen `kubeconfig` Datei, Sie sollten nur ein *ein*-Kontext-Element darin definieren. Siehe https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/["Kubernetes-Dokumentation"^] Weitere Informationen zum Erstellen `kubeconfig` Dateien:



. *Credential Name*: Geben Sie einen Namen für die selbstverwalteten Cluster-Zugangsdaten ein, die Sie auf Astra Control hochladen. Standardmäßig wird der Name der Anmeldeinformationen automatisch als Name des Clusters ausgefüllt.
. *Private Route Identifier*: Dieses Feld ist nur für private Cluster bestimmt.
. Wählen Sie *Weiter*.
. (Optional) *Speicher*: Wählen Sie optional die Storage-Klasse aus, die Kubernetes-Anwendungen, die auf diesem Cluster bereitgestellt werden sollen, standardmäßig verwenden sollen.
+
.. Um eine neue Standard-Storage-Klasse für den Cluster auszuwählen, aktivieren Sie das Kontrollkästchen *Neue Standard-Storage-Klasse zuweisen*.
.. Wählen Sie eine neue Standard-Storage-Klasse aus der Liste aus.
+
[NOTE]
====
Jeder Storage-Service eines Cloud-Providers enthält die folgenden Informationen zu Preis, Performance und Ausfallsicherheit:

ifdef::gcp[]

*** Cloud Volumes Service für Google Cloud: Informationen zu Preis, Performance und Ausfallsicherheit
*** Google Persistent Disk: Keine Informationen über Preis, Performance oder Ausfallsicherheit verfügbar


endif::gcp[]

ifdef::azure[]

*** Azure NetApp Files: Informationen zu Performance und Ausfallsicherheit
*** Azure Managed Disks: Es sind weder Preis-, Performance- oder Resilience-Informationen verfügbar


endif::azure[]

ifdef::aws[]

*** Amazon Elastic Block Store: Keine Informationen zu Preis, Performance oder Ausfallsicherheit verfügbar
*** Amazon FSX für NetApp ONTAP: Keine Informationen zu Preis, Performance und Ausfallsicherheit verfügbar


endif::aws[]

*** NetApp Cloud Volumes ONTAP: Keine Informationen zu Preis, Performance oder Ausfallsicherheit verfügbar


====
+
Jede Storage-Klasse kann einen der folgenden Services nutzen:

+
ifdef::gcp[]

+
*** https://cloud.netapp.com/cloud-volumes-service-for-gcp["Cloud Volumes Service für Google Cloud"^]
*** https://cloud.google.com/persistent-disk/["Google Persistent Disk"^]






endif::gcp[]

ifdef::azure[]

* https://cloud.netapp.com/azure-netapp-files["Azure NetApp Dateien"^]
* https://docs.microsoft.com/en-us/azure/virtual-machines/managed-disks-overview["Von Azure gemanagte Festplatten"^]


endif::azure[]

ifdef::aws[]

* https://docs.aws.amazon.com/ebs/["Amazon Elastic Block Store"^]
* https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX für NetApp ONTAP"^]


endif::aws[]

* https://www.netapp.com/cloud-services/cloud-volumes-ontap/what-is-cloud-volumes/["NetApp Cloud Volumes ONTAP"^]
+
Weitere Informationen zu link:../learn/aws-storage.html["Storage-Klassen für Amazon Web Services Cluster"]. Weitere Informationen zu link:../learn/azure-storage.html["Speicherklassen für AKS-Cluster"]. Weitere Informationen zu link:../learn/choose-class-and-size.html["Speicherklassen für GKE-Cluster"].

+
.. Wählen Sie *Weiter*.
.. *Überprüfen und genehmigen*: Überprüfen Sie die Konfigurationsdetails.
.. Wählen Sie *Add*, um den Cluster zu Astra Control Service hinzuzufügen.






== Ändern der Standard-Storage-Klasse

Sie können die Standard-Storage-Klasse für ein Cluster ändern.



=== Ändern Sie die Standard-Storage-Klasse mit Astra Control

Sie können die Standard-Storage-Klasse für ein Cluster aus Astra Control ändern. Wenn Ihr Cluster einen zuvor installierten Speicher-Backend-Service verwendet, können Sie diese Methode möglicherweise nicht verwenden, um die Standard-Speicherklasse zu ändern (die Aktion *default* ist nicht wählbar). In diesem Fall können Sie <<Ändern Sie die Standard-Storage-Klasse über die Befehlszeile>>.

.Schritte
. Wählen Sie in der Astra Control Service-UI *Cluster* aus.
. Wählen Sie auf der Seite *Cluster* den Cluster aus, den Sie ändern möchten.
. Wählen Sie die Registerkarte *Storage* aus.
. Wählen Sie die Kategorie *Speicherklassen* aus.
. Wählen Sie das Menü *Aktionen* für die Speicherklasse aus, die Sie als Standard festlegen möchten.
. Wählen Sie *als Standard*.




=== Ändern Sie die Standard-Storage-Klasse über die Befehlszeile

Sie können die Standard-Storage-Klasse für ein Cluster mit Kubernetes-Befehlen ändern. Diese Methode funktioniert unabhängig von der Konfiguration Ihres Clusters.

.Schritte
. Melden Sie sich bei Ihrem Kubernetes Cluster an.
. Listen Sie die Storage-Klassen in Ihrem Cluster auf:
+
[source, console]
----
kubectl get storageclass
----
. Entfernen Sie die Standardbezeichnung aus der Standardspeicherklasse. Ersetzen Sie <SC_NAME> durch den Namen der Speicherklasse:
+
[source, console]
----
kubectl patch storageclass <SC_NAME> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
----
. Markieren Sie standardmäßig eine andere Storage-Klasse. Ersetzen Sie <SC_NAME> durch den Namen der Speicherklasse:
+
[source, console]
----
kubectl patch storageclass <SC_NAME> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
----
. Bestätigen Sie die neue Standard-Speicherklasse:
+
[source, console]
----
kubectl get storageclass
----


ifdef::azure[]

endif::azure[]
