---
sidebar: sidebar 
permalink: get-started/intro.html 
keywords: introduction, how astra works, how Astra works, what Astra is, concept, understanding, overview 
summary: Astra Control ist eine Kubernetes-Lösung für das Lifecycle-Management von Applikationsdaten, die den Betrieb zustandsorientierte Applikationen vereinfacht. Schutz, Backup und Migration von Kubernetes-Workloads und sofortige Erstellung von Applikationsklonen 
---
= Weitere Informationen zu Astra Control
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Astra Control ist eine Kubernetes-Lösung für das Lifecycle-Management von Applikationsdaten, die den Betrieb zustandsorientierte Applikationen vereinfacht. Schutz, Backup und Migration von Kubernetes-Workloads und sofortige Erstellung von Applikationsklonen



== Funktionen

Astra Control bietet entscheidende Funktionen für das Lifecycle Management von Kubernetes-Applikationsdaten:

* Automatisches Management von persistentem Storage
* Erstellen Sie applikationsorientierte Snapshots und Backups nach Bedarf
* Automatisierung von richtlinienbasierten Snapshot- und Backup-Vorgängen
* Migrieren Sie Applikationen und Daten von einem Kubernetes-Cluster zu einem anderen
* Replizieren von Applikationen auf ein Remote-System mit NetApp SnapMirror Technologie (Astra Control Center)
* Klonen von Applikationen von Staging hin zur Produktion
* Darstellung des Anwendungszustands und des Schutzstatus
* Verwenden Sie eine Web-Oberfläche oder eine API zur Implementierung Ihrer Backup- und Migration-Workflows




== Implementierungsmodelle

Astra Control ist in zwei Implementierungsmodellen erhältlich:

* *Astra Control Service*: Ein von NetApp gemanagter Service, der applikationskonsistentes Datenmanagement von Kubernetes Clustern in Umgebungen mehrerer Cloud-Provider sowie selbst gemanagte Kubernetes Cluster bietet.
* *Astra Control Center*: Gemanagte Software für applikationsgerechtes Datenmanagement von Kubernetes-Clustern, die in Ihrer On-Premises-Umgebung ausgeführt werden. Astra Control Center kann auch auf mehreren Cloud-Provider-Umgebungen mit einem NetApp Cloud Volumes ONTAP Storage-Backend installiert werden.


[cols="1h,2d,2a"]
|===
|  | Astra Control Service | Astra Control Center 


| Wie wird das angeboten? | Vollständig gemanagter Cloud-Service von NetApp  a| 
Als Software, die Sie herunterladen, installieren und verwalten können



| Wo wird sie gehostet? | In einer Public Cloud von NetApp ihrer Wahl  a| 
In Ihrem eigenen Kubernetes-Cluster



| Wie wird sie aktualisiert? | Gemanagt von NetApp  a| 
Sie verwalten jegliche Updates



| Welche Kubernetes-Distributionen werden unterstützt?  a| 
* *Cloud-Provider*
+
** Amazon Web Services
+
*** Amazon Elastic Kubernetes Service (EKS)


** Google Cloud
+
*** Google Kubernetes Engine (GKE)


** Microsoft Azure
+
*** Azure Kubernetes-Service (AKS)




* *Selbstverwaltete Cluster*
+
** Kubernetes (Vorgelagert)
** Rancher Kubernetes Engine (RKE)
** Red hat OpenShift Container Platform


* *On-Premises-Cluster*
+
** Lokale Red hat OpenShift Container-Plattform



 a| 
* Azure Kubernetes Service für Azure Stack HCI
* Google Anthos
* Kubernetes (Vorgelagert)
* Rancher Kubernetes Engine (RKE)
* Red hat OpenShift Container Platform




| Welche Storage-Back-Ends werden unterstützt?  a| 
* *Cloud-Provider*
+
** Amazon Web Services
+
*** Amazon EBS
*** Amazon FSX für NetApp ONTAP
*** https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-gcp.html["Cloud Volumes ONTAP"^]


** Google Cloud
+
*** Google Persistent Disk
*** NetApp Cloud Volumes Service
*** https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-gcp.html["Cloud Volumes ONTAP"^]


** Microsoft Azure
+
*** Über Azure Gemanagte Festplatten
*** Azure NetApp Dateien
*** https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-azure.html["Cloud Volumes ONTAP"^]




* *Selbstverwaltete Cluster*
+
** Amazon EBS
** Über Azure Gemanagte Festplatten
** Google Persistent Disk
** https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/["Cloud Volumes ONTAP"^]
** NetApp MetroCluster
** https://longhorn.io/["Longhorn"^]


* *On-Premises-Cluster*
+
** NetApp MetroCluster
** NetApp ONTAP AFF und FAS Systeme
** NetApp ONTAP Select
** https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/["Cloud Volumes ONTAP"^]
** https://longhorn.io/["Longhorn"^]



 a| 
* NetApp ONTAP AFF und FAS Systeme
* NetApp ONTAP Select
* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/["Cloud Volumes ONTAP"^]
* https://longhorn.io/["Longhorn"^]


|===


== Funktionsweise des Astra Control Service

Astra Control Service ist ein von NetApp gemanagter Cloud-Service, der ständig verfügbar und mit den neuesten Funktionen aktualisiert ist. Verschiedene Komponenten unterstützen das Lifecycle-Management von Applikationsdaten.

Astra Control Service funktioniert auf hohem Niveau wie folgt:

* Starten Sie mit Astra Control Service, indem Sie Ihren Cloud-Provider einrichten und einen Astra Account anfordern.


ifdef::gcp[]

+ ** für GKE Cluster, Astra Control Service verwendet https://cloud.netapp.com/cloud-volumes-service-for-gcp["NetApp Cloud Volumes Service für Google Cloud"^] Oder Google Persistent Disks als Storage-Backend für Ihre persistenten Volumes.

endif::gcp[]

ifdef::azure[]

+ ** für AKS-Cluster, Astra Control Service verwendet https://cloud.netapp.com/azure-netapp-files["Azure NetApp Dateien"^] Oder von Azure gemanagte Festplatten als Storage-Backend für Ihre persistenten Volumes.

endif::azure[]

ifdef::aws[]

+ ** für Amazon EKS Cluster, Astra Control Service verwendet https://docs.aws.amazon.com/ebs/["Amazon Elastic Block Store"^] Oder https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX für NetApp ONTAP"^] Das Storage-Backend für Ihre persistenten Volumes

endif::aws[]

* Sie fügen Ihre ersten Kubernetes-Computing-Ressourcen in den Astra Control Service ein. Astra Control Service übernimmt dann Folgendes:
+
** Erstellung eines Objektspeicher in Ihrem Cloud-Provider-Konto, an dem Backup-Kopien gespeichert werden




ifdef::azure[]

+ in Azure erstellt Astra Control Service außerdem eine Ressourcengruppe, ein Storage-Konto und Schlüssel für den Blob-Container.

endif::azure[]

* Erstellt eine neue Administratorrolle und ein Kubernetes-Servicekonto auf dem Cluster.
* Verwendet diese neue Administratorrolle, um den Link../concepts/architecture#astra-control-components[Astra Control Provisioner] auf dem Cluster zu installieren und eine oder mehrere Storage-Klassen zu erstellen.
* Wenn Sie ein Storage-Angebot mit NetApp Cloud-Services als Storage-Back-End verwenden, stellt Astra Control Service persistente Volumes für Ihre Applikationen bereit. Wenn Sie von Amazon EBS oder Azure gemanagte Festplatten als Storage-Backend verwenden, müssen Sie einen Provider-spezifischen CSI-Treiber installieren. Installationsanweisungen finden Sie in link:set-up-amazon-web-services.html["Einrichten von Amazon Web Services"^] Und link:set-up-microsoft-azure-with-amd.html["Richten Sie Microsoft Azure mit von Azure gemanagten Festplatten ein"^].
+
** An diesem Punkt können Sie Apps aus Ihrem Cluster definieren. Persistente Volumes werden auf dem Storage-Back-End über die neue Standard-Storage-Klasse bereitgestellt.
** Anschließend verwalten Sie diese Applikationen mithilfe des Astra Control Service und erstellen Snapshots, Backups und Klone.




Mit dem kostenlosen Plan von Astra Control können Sie bis zu 10 Namespaces in Ihrem Konto verwalten. Wenn Sie mehr als 10 Namespaces verwalten möchten, müssen Sie die Abrechnung durch ein Upgrade vom kostenlosen Plan auf den Premium-Plan einrichten.



== So funktioniert Astra Control Center

Astra Control Center wird lokal in Ihrer eigenen Private Cloud ausgeführt.

Astra Control Center unterstützt Kubernetes-Cluster mit einer für die Astra Control Provisioner konfigurierten Storage-Klasse mit einem ONTAP Storage-Back-End.

Astra Control Center ist vollständig in das Ecosystem von AutoSupport und Active IQ Digital Advisor (auch als digitaler Berater bekannt) integriert, um Benutzern und NetApp-Support Fehlerbehebungs- und Verwendungsinformationen zu bieten.

Sie können Astra Control Center mit einer 90-Tage-Evaluierungslizenz ausprobieren. Die Evaluierungsversion wird durch E-Mail- und Community-Optionen unterstützt. Zudem haben Sie über das Dashboard für den Produktsupport Zugriff auf Knowledgebase-Artikel und -Dokumentation.

Um Astra Control Center zu installieren und zu verwenden, müssen Sie sicher sein https://docs.netapp.com/us-en/astra-control-center/get-started/requirements.html["Anforderungen"].

Astra Control Center funktioniert auf hohem Niveau wie folgt:

* Sie installieren Astra Control Center in Ihrer lokalen Umgebung. Erfahren Sie mehr darüber, wie Sie https://docs.netapp.com/us-en/astra-control-center/get-started/install_acc.html["Installieren Sie Astra Control Center"].
* Sie führen einige Setup-Aufgaben wie die folgenden aus:
+
** Lizenzierung einrichten.
** Fügen Sie den ersten Cluster hinzu.
** Fügen Sie ein Storage-Back-End hinzu, das beim Hinzufügen des Clusters erkannt wird.
** Fügen Sie einen Objektspeicher-Bucket hinzu, der Ihre Applikations-Backups speichert.




Erfahren Sie mehr darüber, wie Sie https://docs.netapp.com/us-en/astra-control-center/get-started/setup_overview.html["Einrichten des Astra Control Center"].

Sie können Applikationen zu Ihrem Cluster hinzufügen. Wenn auch einige Applikationen bereits im Cluster gemanagt werden, können Sie sie mit Astra Control Center managen. Nutzen Sie dann das Astra Control Center, um Snapshots, Backups, Klone und Replizierungsbeziehungen zu erstellen.



== Finden Sie weitere Informationen

* https://docs.netapp.com/us-en/astra-family/["Dokumentation zur NetApp Astra Produktfamilie"^]
* https://docs.netapp.com/us-en/astra-control-center/index.html["Astra Control Center-Dokumentation"^]
* https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API-Dokumentation"^]
* https://docs.netapp.com/us-en/trident/index.html["Astra Trident-Dokumentation"^]
* https://docs.netapp.com/us-en/ontap/index.html["ONTAP-Dokumentation"^]

