---
sidebar: sidebar 
permalink: get-started/manage-private-cluster.html 
keywords: discover private cluster, add cluster, add kubernetes cluster, private, discover kubernetes cluster, add private cluster 
summary: Nach der Einrichtung der Umgebung erstellen Sie sofort einen Kubernetes Cluster und fügen ihn dann dem Astra Control Service hinzu. 
---
= Managen Sie private Cluster über den Astra Control Service
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Mit Astra Control Service können Sie private Azure Kubernetes Service (AKS)-Cluster sowie private Red hat OpenShift-Cluster in AKS managen. In diesen Anweisungen wird davon ausgegangen, dass Sie bereits einen privaten AKS- oder OpenShift-Cluster erstellt und eine sichere Methode für den Remote-Zugriff darauf vorbereitet haben. Weitere Informationen zum Erstellen und Zugreifen auf private AKS- oder OpenShift-Cluster finden Sie in der folgenden Dokumentation:

* https://["Azure-Dokumentation für private AKS-Cluster"^]
* https://["Azure-Dokumentation für private OpenShift-Cluster"^]




== Installieren Sie den Astra Connector Operator

Sie müssen den Astra Connector Operator auf dem privaten Cluster installieren. Wenn Sie einen Bastion-Host verwenden, geben Sie diese Befehle über die Befehlszeile des Bastion-Hosts aus.

.Schritte
. Klonen des GitHub-Repositorys des Astra Connector-Betreibers:
+
[source, console]
----
git clone https://github.com/NetApp/astra-connector-operator.git
----
. Ändern Sie die Verzeichnisse auf die oberste Ebene des entpackten Bedienerpakets, damit Sie die sehen können `astraconnector_operator.yaml` Datei mit `ls` Befehl.
. Erstellen Sie einen Namespace für den Astra Connector Operator.
+
[source, console]
----
kubectl create ns astra-connector-operator
----
. Anwenden des `astraconnector_operator.yaml` Datei zum Namespace des Bedieners.
+
[source, console]
----
kubectl apply -f astraconnector_operator.yaml -n astra-connector-operator
----
. Erstellen Sie einen Namespace für die privaten Clusterkomponenten.
+
[source, console]
----
kubectl create ns astra-connector
----
. Generieren Sie mithilfe der Anweisungen im ein Astra Control API-Token https://["Dokumentation von Astra Automation"^].
. Ändern Sie die Beispielkonfigurationsdatei im Verzeichnis config/Samples des Astra Connector Operator Repository, um den einzuschließen `spec.natssync-client.cloud-bridge-url` Taste. Beispiel:
+
[listing]
----
apiVersion: netapp.astraconnector.com/v1
kind: AstraConnector
metadata:
  name: astra-connector
spec:
  natssync-client:
    image: natssync-client:2.0
    cloud-bridge-url: https://<your.astra.control.service.url>
  nats:
    image: nats:2.6.1-alpine3.14
  httpproxy-client:
    image: httpproxylet:2.0
  echo-client:
    image: echo-proxylet:2.0
  imageRegistry:
    name: theotw
  astra:
    token: <Astra Control API token>
    clusterName: <your-cluster-name>
    accountId: <Astra Control account id>
    acceptEULA: yes
----
. Wenden Sie die Astra Connector Custom Resource Definition (CRD) an.
+
[source, console]
----
kubectl apply -f config/samples/astraconnector_v1.yaml -n astra-connector
----
. Überprüfen Sie den Status des Astra Connectors.
+
[source, console]
----
kubectl get astraconnector astra-connector -n astra-connector
----
+
Sie sollten sich auf die Ausgabe beziehen, die der folgenden ähnelt:

+
[source, console]
----
NAME              REGISTERED   ASTRACONNECTORID
astra-connector   true         22b839aa-8b85-445a-85dd-0b1f53b5ea19
----




== Einrichtung von persistentem Storage

Konfigurieren Sie persistenten Storage für das Cluster. Sie können gemanagte Azure NetApp Files oder Azure Festplatten verwenden. Weitere Informationen zur Konfiguration von Azure mit diesen Optionen finden Sie in der Dokumentation zu Einstieg:

* https://["Microsoft Azure mit Azure NetApp Files einrichten"]
* https://["Richten Sie Microsoft Azure mit von Azure gemanagten Festplatten ein"]




== Fügen Sie den privaten Cluster zum Astra Control Service hinzu

Sie können den privaten Cluster jetzt dem Astra Control Service hinzufügen. Folgen Sie dem Standard-Workflow, um dem Astra Control Service ein Cluster hinzuzufügen: https://["Managen Sie Kubernetes Cluster über den Astra Control Service"].
