---
sidebar: sidebar 
permalink: get-started/register.html 
keywords: BlueXP, sign up, log in, login, register, register for BlueXP, create account, sign up for account, get an account, account, accounts 
summary: Der Astra Control Service ist in den Authentifizierungsservice von NetApp BlueXP integriert. Melden Sie sich bei BlueXP an, um auf Astra Control Service und andere NetApp Cloud-Services zuzugreifen. 
---
= Registrieren Sie sich für ein Astra Control Service-Konto
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Um Astra Control Service nutzen zu können, benötigen Sie ein Astra Control Service Konto, das zu Ihrem NetApp BlueXP Konto verknüpft ist. Füllen Sie den Registrierungsprozess für Astra Control Service aus, und wenn Sie noch kein BlueXP Konto besitzen, melden Sie sich bei BlueXP an, um auf den Astra Control Service zuzugreifen.



== Registrieren Sie sich für ein Astra Control Konto

Bevor Sie sich beim Astra Control Service anmelden können, müssen Sie einen Registrierungsvorgang abschließen, um ein Astra Control Service-Konto zu erhalten.

Wenn Sie den Astra Control Service nutzen, verwalten Sie Ihre Apps über ein Konto. Ein Konto umfasst Benutzer, die die Apps im Konto anzeigen und verwalten können, sowie Ihre Rechnungsdaten.

.Schritte
. https://cloud.netapp.com/astra["Wechseln Sie zur Seite Astra Control bei BlueXP"^].
. Wählen Sie *Anmeldung für den kostenlosen Plan*.
. Geben Sie die erforderlichen Informationen in das Formular ein.
+
Beim Ausfüllen des Formulars sind einige wichtige Punkte zu beachten:

+
** Ihr Unternehmensname und Ihre Adresse müssen korrekt sein, da wir sie überprüfen, um die Anforderungen der Global Trade Compliance zu erfüllen.
** Der *Astra-Kundenname* ist der Name Ihres Astra Control Service-Kontos. Diesen Namen sehen Sie in der Benutzeroberfläche des Astra Control Service. Beachten Sie, dass Sie bei Bedarf weitere Konten (bis zu 5) erstellen können.
** Wenn Sie ein NetApp BlueXP Konto haben, geben Sie im Feld *geschäftliche E-Mail-Adresse* die E-Mail ein, die Sie für dieses Konto verwenden. Wenn Sie noch kein NetApp BlueXP Konto haben, verwenden Sie bei Ihrer Anmeldung zu BlueXP die hier eingegebene E-Mail-Adresse.


. Wählen Sie *Konto Erstellen*.




== Melden Sie sich bei BlueXP an

Der Astra Control Service ist in den Authentifizierungsservice von NetApp BlueXP integriert. Sie können sich mit Ihren Zugangsdaten für die BlueXP oder die NetApp Support-Website bei NetApp BlueXP anmelden. Wenn Sie noch kein NetApp BlueXP oder NetApp Support Site Konto haben, melden Sie sich bei BlueXP an. Damit haben Sie Zugriff auf Astra Control Service und weitere Cloud-Services von NetApp. Wenn Sie bereits über ein BlueXP oder NetApp Konto verfügen und die Registrierung abgeschlossen haben, können Sie darauf zugreifen https://astra.netapp.io["Astra Control Service"^] Sie können Ihre Anmeldedaten für BlueXP oder die NetApp Support-Website direkt verwenden.


TIP: Sie können sich auch mit Single Sign-On über Anmeldedaten Ihres Unternehmensverzeichnisses bei BlueXP anmelden (föderierte Identität). Weitere Informationen erhalten Sie im https://cloud.netapp.com/help-center["Hilfe-Center"^] Und wählen Sie dann *Cloud Central Anmelde-Optionen*.

.Schritte
. Gehen Sie zu https://cloud.netapp.com["NetApp BlueXP"^].
. Wählen Sie oben rechts *erste Schritte*.
. Wählen Sie *Registrieren*.
. Füllen Sie das Formular aus.
+
Stellen Sie sicher, dass die Telefonnummer und die E-Mail-Adresse, die Sie hier eingeben, mit denen übereinstimmen, die Sie im vorherigen Astra Control-Registrierungsformular verwendet haben.

. Wählen Sie *Registrieren*.
+

TIP: Die E-Mail-Adresse, die Sie in diese Formulare eingeben, gilt für Ihre NetApp BlueXP Benutzer-ID. Verwenden Sie diese BlueXP Benutzer-ID, wenn Sie sich für ein neues Astra Control Konto anmelden oder wenn ein Astra Control Administrator Sie zu einem vorhandenen Astra Control Konto einlädt.

. Warten Sie auf eine E-Mail von NetApp BlueXP. Die E-Mail-Adresse stammt von saas.support@netapp.com und kann einige Minuten dauern. Überprüfen Sie Ihren Spam-Ordner.
. Wenn die E-Mail eintrifft, wählen Sie den Link in der E-Mail aus, um Ihre E-Mail-Adresse zu überprüfen.


.Ergebnis
Sie verfügen jetzt über eine aktive BlueXP Benutzeranmeldung.

Da Sie jetzt registriert sind, können Sie mit Ihren BlueXP Zugangsdaten direkt auf Astra Control zugreifen https://astra.netapp.io[].
