---
sidebar: sidebar 
permalink: get-started/set-up-amazon-web-services.html 
keywords: set up service account, create service account, project, permissions, service account permissions, key, service account key, json, key json, roles, service account roles, apis, networking, private service access, kubernetes cluster, cluster requirements, version requirements, supported versions, supported regions, kubernetes version, ubuntu, image type, networking, container os 
summary: Zur Vorbereitung Ihres Amazon Web Services Projekts sind einige Schritte erforderlich, bevor Sie Amazon Elastic Kubernetes Service Cluster mit Astra Control Service managen können. 
---
= Einrichten von Amazon Web Services
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


Zur Vorbereitung Ihres Amazon Web Services Projekts sind einige Schritte erforderlich, bevor Sie Amazon Elastic Kubernetes Service (EKS) Cluster mit Astra Control Service managen können.



== Schnellstart für die Einrichtung von Amazon Web Services

Führen Sie diese Schritte schnell durch, oder scrollen Sie nach unten zu den verbleibenden Abschnitten, um ausführliche Informationen zu erhalten.



=== Astra Control Service-Anforderungen für Amazon Web Services überprüfen

[role="quick-margin-para"]
Stellen Sie sicher, dass die Cluster ordnungsgemäß sind und eine unterstützte Version von Kubernetes ausführen, dass Worker-Nodes unter anderem Linux oder Windows online sind.  cluster requirements,Erfahren Sie mehr zu diesem Schritt.



=== Erstellen Sie ein Amazon-Konto

[role="quick-margin-para"]
Wenn Sie noch kein Amazon-Konto haben, müssen Sie ein Konto erstellen, damit Sie EKS verwenden können.  an Amazon account,Erfahren Sie mehr zu diesem Schritt.



=== Installieren Sie die Amazon Web Services-CLI

[role="quick-margin-para"]
Installieren Sie die AWS CLI, sodass Sie AWS über die Befehlszeile managen können.  the Amazon Web Services CLI,Befolgen Sie die Schritt-für-Schritt-Anweisungen.



=== Optional: Erstellen Sie einen IAM-Benutzer

[role="quick-margin-para"]
Erstellen Sie einen Amazon IAM-Benutzer (Identity and Access Management). Sie können diesen Schritt auch überspringen und einen vorhandenen IAM-Benutzer mit Astra Control Service verwenden.

[role="quick-margin-para"]
 Create an IAM user,Lesen Sie Schritt-für-Schritt-Anleitungen.



=== Erstellen Sie eine Berechtigungsrichtlinie und fügen Sie sie an

[role="quick-margin-para"]
Erstellen einer Richtlinie mit den erforderlichen Berechtigungen für den Astra Control Service zur Interaktion mit Ihrem AWS Konto

[role="quick-margin-para"]
 and attach a permissions policy,Lesen Sie Schritt-für-Schritt-Anleitungen.



=== Speichern Sie die Anmeldeinformationen für den IAM-Benutzer

[role="quick-margin-para"]
Speichern Sie die Anmeldeinformationen für den IAM-Benutzer, damit Sie die Anmeldeinformationen in den Astra Control Service importieren können.

[role="quick-margin-para"]
 the credentials for the IAM user,Lesen Sie Schritt-für-Schritt-Anleitungen.



== EKS-Clusteranforderungen

Ein Kubernetes-Cluster muss folgende Anforderungen erfüllen, damit Sie ihn über den Astra Control Service erkennen und managen können.

Kubernetes-Version:: Auf einem Cluster muss eine Kubernetes-Version im Bereich von 1.20 bis 1.22 ausgeführt werden.
Bildtyp:: Der Bildtyp für jeden Arbeiterknoten muss Linux sein.
Der Cluster-Status:: Cluster müssen in einem ordnungsgemäßen Zustand ausgeführt werden und mindestens einen Online-Worker-Node ohne „Worker“-Nodes im ausgefallenen Status aufweisen.


Astra Trident für Amazon FSX für NetApp ONTAP:: Wenn Sie das Backend von Amazon FSX für NetApp ONTAP Storage nutzen, müssen Sie Astra Trident installieren. Anweisungen hierzu finden Sie unter https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy.html["Astra Trident – Übersicht über die Implementierung"^]. Weitere Informationen zur Verwendung von Astra Trident mit FSX für NetApp ONTAP finden Sie unter https://docs.netapp.com/us-en/trident/trident-use/trident-fsx.html["Setzen Sie Astra Trident mit Amazon FSX für NetApp ONTAP ein"^].
CSI-Treiber für Amazon Elastic Block Store (EBS):: Wenn Sie das Amazon EBS Storage-Backend verwenden, müssen Sie den Container Storage Interface (CSI)-Treiber für EBS installieren (dieser wird nicht automatisch installiert).
+
--
Anweisungen zur Installation des CSI-Treibers finden Sie in den entsprechenden Einzelheiten.

====
.Installieren Sie einen externen Schnappschussfilter
. Erstellen von Volume Snapshot-CRDs.
+
Verwenden Sie für Kubernetes ab Version 1.20 v1 Snapshot-CRDs mit Snapshot-Komponenten von v5.0.

+
[role="tabbed-block"]
=====
.V5.0-Komponenten
--
[source, yaml]
----
$ cat snapshot-setup.sh
#!/bin/bash
# Create volume snapshot CRDs
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-5.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-5.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-5.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
----
--
=====
. Erstellen Sie den Snapshot-Controller im gewünschten Namespace. Bearbeiten Sie die YAML-Manifeste unten, um den Namespace zu ändern.
+
Für Kubernetes 1.20 und höher verwenden Sie v5.0.

+
[role="tabbed-block"]
=====
.V5.0-Controller
--
[source, yaml]
----
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-5.0/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-5.0/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
----
--
=====


.Den CSI-Treiber als Amazon EKS-Add-On installieren
. Erstellen der IAM-Rolle des Amazon EBS CSI-Treibers für Service-Konten Befolgen Sie die Anweisungen https://docs.aws.amazon.com/eks/latest/userguide/csi-iam-role.html["In der Amazon-Dokumentation"^], Verwenden der AWS CLI-Befehle in den Anweisungen.
. Fügen Sie das Amazon EBS CSI-Add-on mit dem folgenden AWS-CLI-Befehl hinzu und ersetzen Sie Informationen in Klammern <> durch Werte speziell für Ihre Umgebung. Ersetzen Sie <DRIVER_ROLE> durch den Namen der EBS CSI-Treiberrolle, die Sie im vorherigen Schritt erstellt haben:
+
[source, sh]
----
aws eks create-addon \
  --cluster-name <CLUSTER_NAME> \
  --addon-name aws-ebs-csi-driver \
  --service-account-role-arn arn:aws:iam::<ACCOUNT_ID>:role/<DRIVER_ROLE>
----


.Konfigurieren der EBS Storage-Klasse
. Klonen Sie das GitHub Repository des Amazon EBS CSI-Treibers auf Ihrem System.
+
[source, sh]
----
git clone https://github.com/kubernetes-sigs/aws-ebs-csi-driver.git
----
. Navigieren Sie zum Beispielverzeichnis für dynamische Bereitstellung.
+
[source, sh]
----
cd aws-ebs-csi-driver/examples/kubernetes/dynamic-provisioning/
----
. Implementierung der ebs-sc-Storage-Klasse und der ebs-Claim Persistent Volume Claim aus dem Manifeste Verzeichnis
+
[source, sh]
----
kubectl apply -f manifests/storageclass.yaml
kubectl apply -f manifests/claim.yaml
----
. ebs-sc Storage-Klasse beschreiben
+
[source, sh]
----
kubectl describe storageclass ebs-sc
----
+
Sie sollten die Ausgabe sehen, in der die Attribute der Storage-Klasse beschrieben werden.



====
--




== Erstellen Sie ein Amazon-Konto

Wenn Sie noch kein Amazon-Konto besitzen, müssen Sie ein Konto erstellen, um die Abrechnung für Amazon EKS zu aktivieren.

.Schritte
. Wechseln Sie zum https://www.amazon.com["Amazon Homepage"^] Wählen Sie oben rechts *Anmelden* und wählen Sie *Hier starten*.
. Befolgen Sie die Anweisungen, um ein Konto zu erstellen.




== Installieren Sie die Amazon Web Services-CLI

Installieren Sie die AWS CLI, sodass Sie AWS Ressourcen über die Befehlszeile managen können.

.Schritt
. Gehen Sie zu https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html["Erste Schritte mit der AWS CLI"^] Und befolgen Sie die Anweisungen zur Installation der CLI.




== Optional: Erstellen Sie einen IAM-Benutzer

Erstellen Sie einen IAM-Benutzer, damit Sie AWS Services und Ressourcen mit erhöhter Sicherheit nutzen und managen können. Sie können diesen Schritt auch überspringen und einen vorhandenen IAM-Benutzer mit Astra Control Service verwenden.

.Schritt
. Gehen Sie zu https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_create.html#id_users_create_cliwpsapi["IAM-Benutzer werden erstellt"^] Und befolgen Sie die Anweisungen zum Erstellen eines IAM-Benutzers.




== Erstellen Sie eine Berechtigungsrichtlinie und fügen Sie sie an

Erstellen einer Richtlinie mit den erforderlichen Berechtigungen für den Astra Control Service zur Interaktion mit Ihrem AWS Konto

.Schritte
. Erstellen Sie eine neue Datei mit dem Namen `policy.json`.
. Kopieren Sie den folgenden JSON-Inhalt in die Datei:
+
[source, JSON]
----
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "cloudwatch:GetMetricData",
                "fsx:DescribeVolumes",
                "ec2:DescribeRegions",
                "s3:CreateBucket",
                "s3:ListBucket",
                "s3:PutObject",
                "s3:GetObject",
                "iam:SimulatePrincipalPolicy",
                "s3:ListAllMyBuckets",
                "eks:DescribeCluster",
                "eks:ListNodegroups",
                "eks:DescribeNodegroup",
                "eks:ListClusters",
                "iam:GetUser",
                "s3:DeleteObject",
                "s3:DeleteBucket",
                "autoscaling:DescribeAutoScalingGroups"
            ],
            "Resource": "*"
        }
    ]
}
----
. Erstellen der Richtlinie:
+
[source, sh]
----
POLICY_ARN=$(aws iam create-policy  --policy-name <policy-name> --policy-document file://policy.json  --query='Policy.Arn' --output=text)
----
. Hängen Sie die Richtlinie an den IAM-Benutzer an. Austausch `<IAM-USER-NAME>` Entweder mit dem Benutzernamen des von Ihnen erstellten IAM-Benutzers oder mit einem vorhandenen IAM-Benutzer:
+
[source, sh]
----
aws iam attach-user-policy --user-name <IAM-USER-NAME> --policy-arn=$POLICY_ARN
----




== Speichern Sie die Anmeldeinformationen für den IAM-Benutzer

Speichern Sie die Anmeldeinformationen für den IAM-Benutzer, damit Sie den Astra Control Service auf den Benutzer aufmerksam machen können.

.Schritte
. Anmeldedaten herunterladen Austausch `<IAM-USER-NAME>` Mit dem Benutzernamen des IAM-Benutzers, den Sie verwenden möchten:
+
[source, sh]
----
aws iam create-access-key --user-name <IAM-USER-NAME> --output json > credential.json
----


Der `credential.json` Datei ist erstellt, und Sie können die Anmeldeinformationen in Astra Control Service importieren.
