---
sidebar: sidebar 
permalink: get-started/supported-deployments.html 
keywords: gke, aks, google kubernetes engine, azure kubernetes service 
summary: Astra Control Service kann Applikationen managen, die auf einem gemanagten Kubernetes Cluster in Cloud-Provider-Umgebungen ausgeführt werden. 
---
= Unterstützte Kubernetes-Implementierungen
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Astra Control Service managt Applikationen, die auf einem gemanagten Kubernetes-Cluster in Amazon Elastic Kubernetes Service (EKS) ausgeführt werden, sowie Cluster, die Sie selbst managen.

Astra Control Service kann sowohl auf einem gemanagten Kubernetes-Cluster in der Google Kubernetes Engine (GKE) als auch auf Clustern, die Sie selbst managen, ausgeführte Applikationen managen.

Astra Control Service kann Apps managen, die auf einem gemanagten Kubernetes-Cluster in Azure Kubernetes Service (AKS) ausgeführt werden, sowie Cluster, die Sie selbst managen.

ifdef::aws[]

* link:set-up-amazon-web-services.html["Erfahren Sie, wie Sie Amazon Web Services für Astra Control Service einrichten"].


endif::aws[]

ifdef::gcp[]

* link:set-up-google-cloud.html["Erfahren Sie, wie Sie Google Cloud für Astra Control Service einrichten"].


endif::gcp[]

ifdef::azure[]

* link:set-up-microsoft-azure-with-anf.html["Erfahren Sie, wie Sie Microsoft Azure mit Azure NetApp Files für Astra Control Service einrichten"].
* link:set-up-microsoft-azure-with-amd.html["Erfahren Sie, wie Sie Microsoft Azure mit gemanagten Azure Festplatten für den Astra Control Service einrichten"].


endif::azure[]

* link:add-first-cluster.html#start-managing-kubernetes-clusters["Bereiten Sie selbst gemanagte Cluster vor, bevor Sie sie in den Astra Control Service hinzufügen"].

