---
sidebar: sidebar 
permalink: get-started/videos.html 
keywords: videos, Astra Control Service videos 
summary: 'Viele der Seiten auf dieser doc-Site enthalten Videos, die zeigen, wie man mit Astra Control Service eine Aufgabe erledigt. Wenn Sie nur an Videos interessiert sind, haben wir es Ihnen leichter gemacht, indem Sie alle Videos auf dieser einzelnen Seite sammeln (ähnlich einer Playlist).' 
---
= Videos des Astra Control Service
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Viele der Seiten auf dieser doc-Site enthalten Videos, die Ihnen zeigen, wie Sie eine Aufgabe für den Astra Control Service erledigen können. Wenn Sie nur an Videos interessiert sind, haben wir es Ihnen leicht gemacht, indem Sie alle Videos auf dieser einzelnen Seite sammeln (ähnlich einer Playlist).

ifdef::gcp[]



== Videos zum Einrichten von Google Cloud

In den folgenden Videos wird gezeigt, wie die Einrichtung in Google Cloud abgeschlossen wird, bevor Kubernetes Cluster in GCP erkannt werden können.



=== Aktivieren Sie APIs

Für Ihr Projekt sind Berechtigungen erforderlich, um auf bestimmte Google Cloud-APIs zuzugreifen. Das folgende Video zeigt, wie die APIs über die Google Cloud-Konsole aktiviert werden. link:set-up-google-cloud.html#enable-apis-in-your-project["Erfahren Sie mehr über die Aktivierung von APIs"].

video::get-started/video-enable-gcp-apis.mp4[width=848,height=480]


=== Erstellen eines Dienstkontos

Astra Control Service nutzt ein Google Cloud-Service-Konto, um das Management von Kubernetes-Applikationsdaten in Ihrem Auftrag zu vereinfachen. Das folgende Video zeigt, wie Sie das Servicekonto über die Google Cloud-Konsole erstellen. link:set-up-google-cloud.html#create-a-service-account["Erfahren Sie mehr über das Erstellen eines Servicekontos"].

video::get-started/video-create-gcp-service-account.mp4[width=848,height=480]


=== Erstellen eines Service-Kontokonschlüssels

Astra Control Service verwendet einen Service-Account-Schlüssel, um die Identität des Service-Kontos zu ermitteln, das Sie gerade eingerichtet haben. Das folgende Video zeigt, wie der Service-Kontokschlüssel über die Google Cloud-Konsole erstellt wird. link:set-up-google-cloud.html#create-a-service-account-key-2["Erfahren Sie mehr über das Erstellen eines Service-Kontokonschlüssels"].

video::get-started/video-create-gcp-service-account-key.mp4[width=848,height=480]
endif::gcp[]



== Videos zur Verwendung von Astra Control

In den folgenden Videos wird gezeigt, wie Sie gängige Aufgaben mit Astra Control ausführen.



=== Management von Clustern über Astra Control

Nachdem Sie sich beim Astra Control Service angemeldet haben, müssen Sie zunächst Kubernetes-Computing hinzufügen. link:add-first-cluster.html["Erfahren Sie mehr über das Managen von Clustern"].

video::get-started/video-manage-cluster.mp4[width=848,height=480]


=== Konfigurieren einer Sicherungsrichtlinie

Eine Sicherungsrichtlinie sichert eine Applikation, indem Snapshots, Backups oder beides nach einem definierten Zeitplan erstellt werden. Sie können Snapshots und Backups stündlich, täglich, wöchentlich und monatlich erstellen. Außerdem können Sie die Anzahl der beizubehaltenden Kopien festlegen. link:../use/protect-apps.html["Weitere Informationen zum Konfigurieren von Sicherungsrichtlinien"].

video::use/video-set-protection-policy.mp4[width=848,height=480]