---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: bugs, known issues, problems 
summary: Bekannte Probleme identifizieren Probleme, die Sie daran hindern könnten, diese Produktversion erfolgreich zu verwenden. 
---
= Bekannte Probleme
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/release-notes/


[role="lead"]
Bekannte Probleme identifizieren Probleme, die Sie daran hindern könnten, diese Produktversion erfolgreich zu verwenden.

Die folgenden bekannten Probleme wirken sich auf die aktuelle Version aus:

.Anwendungen
* <<Eine App kann nicht in einem Namespace definiert werden, der gelöscht und neu erstellt wurde>>


.Backup, Wiederherstellung und Klonen
* <<Applikationsklone können nicht mit einer bestimmten Version von PostgreSQL verwendet werden>>
* <<App-Backups und Snapshots schlagen fehl, wenn die Volume-Snapshot-Klasse nach dem Management eines Clusters hinzugefügt wird>>


.Andere Probleme
* <<Das Management der App-Daten schlägt mit Fehler des internen Service (500) fehl, wenn Astra Trident offline ist>>




== Eine App kann nicht in einem Namespace definiert werden, der gelöscht und neu erstellt wurde

Wenn Sie eine Anwendung mit einem Namespace definieren, löschen Sie den Namespace und installieren Sie die App anschließend im selben Namespace neu, schlägt der Vorgang mit einem Fehlercode 409 fehl. Um die App mit dem neu erstellten Namespace zu definieren, löschen Sie zuerst die alte Applikationsinstanz.



== Applikationsklone können nicht mit einer bestimmten Version von PostgreSQL verwendet werden

App-Klone innerhalb desselben Clusters schlagen konsequent mit dem Bitnami PostgreSQL 11.5.0 Diagramm fehl. Um erfolgreich zu klonen, verwenden Sie eine frühere oder höhere Version des Diagramms.



== App-Backups und Snapshots schlagen fehl, wenn die Volume-Snapshot-Klasse nach dem Management eines Clusters hinzugefügt wird

Backups und Snapshots schlagen in diesem Szenario mit einem UI 500-Fehler fehl. Aktualisieren Sie die App-Liste als Workaround.



== Das Management der App-Daten schlägt mit Fehler des internen Service (500) fehl, wenn Astra Trident offline ist

Wenn Astra Trident auf einem App-Cluster offline geschaltet wird (und wieder online geschaltet wird) und 500 interne Servicefehler auftreten, wenn versucht wird, das App-Datenmanagement zu managen, starten Sie alle Kubernetes-Nodes im App-Cluster neu, um die Funktionalität wiederherzustellen.
