---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: bugs, known issues, problems 
summary: Bekannte Probleme identifizieren Probleme, die Sie daran hindern könnten, diese Produktversion erfolgreich zu verwenden. 
---
= Bekannte Probleme
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/release-notes/


[role="lead"]
Bekannte Probleme identifizieren Probleme, die Sie daran hindern könnten, diese Produktversion erfolgreich zu verwenden.

Die folgenden bekannten Probleme wirken sich auf die aktuelle Version aus:

.Anwendungen
*  clones fail after an application is deployed with a set storage class
*  page loads forever when trying to restore an application belonging to a deleted cluster
*  to define an app on a namespace that has been deleted and recreated


.Backup, Wiederherstellung und Klonen
*  of an app results in PV size larger than original PV
*  clones fail using a specific version of PostgreSQL
*  backups and snapshots fail if the volumesnapshotclass is added after a cluster is managed


ifdef::azure[]

*  backup buckets use LRS redundancy by default


endif::azure[]

.Andere Probleme
*  eventually begin to fail when using external-snapshotter version 4.2.0
*  data management operations fail with Internal Service Error (500) when Astra Trident is offline




== Applikationsklone scheitern, nachdem eine Applikation mit einer festgelegten Storage-Klasse implementiert wurde

Nachdem eine Applikation mit einer Storage-Klasse bereitgestellt wurde (z. B. `helm install ...-set global.storageClass=netapp-cvs-perf-extreme`). Nachfolgende Klonversuche der Applikation erfordern, dass das Ziel-Cluster die ursprünglich angegebene Storage-Klasse hat. Das Klonen einer Applikation mit einer explizit festgelegten Storage-Klasse auf ein Cluster ohne dieselbe Storage-Klasse schlägt fehl. Es gibt keine Wiederherstellungsschritte in diesem Szenario.



== Die Anwendungsseite wird dauerhaft geladen, wenn versucht wird, eine Applikation, die zu einem gelöschten Cluster gehört, wiederherzustellen

Wenn Sie versuchen, eine Anwendung aus einem gelöschten Cluster von der Seite Anwendungen wiederherzustellen, wird das Laden der Seite Anwendungen nie beendet. Stellen Sie die App als Problemumgehung im Menü Aktionen der App auf der Liste Anwendungen wieder her.



== Eine App kann nicht in einem Namespace definiert werden, der gelöscht und neu erstellt wurde

Wenn Sie eine Anwendung mit einem Namespace definieren, löschen Sie den Namespace und installieren Sie die App anschließend im selben Namespace neu, schlägt der Vorgang mit einem Fehlercode 409 fehl. Um die App mit dem neu erstellten Namespace zu definieren, löschen Sie zuerst die alte Applikationsinstanz.



== Die Wiederherstellung einer App führt zu einer PV-Größe, die größer ist als das ursprüngliche PV

Wenn Sie ein persistentes Volume nach der Erstellung eines Backups skalieren und dann aus diesem Backup wiederherstellen, wird die Größe des persistenten Volumes an die neue PV-Größe angepasst, anstatt die Backup-Größe zu verwenden.



== Applikationsklone können nicht mit einer bestimmten Version von PostgreSQL verwendet werden

App-Klone innerhalb desselben Clusters schlagen konsequent mit dem Bitnami PostgreSQL 11.5.0 Diagramm fehl. Um erfolgreich zu klonen, verwenden Sie eine frühere oder höhere Version des Diagramms.



== App-Backups und Snapshots schlagen fehl, wenn die Volume-Snapshot-Klasse nach dem Management eines Clusters hinzugefügt wird

Backups und Snapshots schlagen in diesem Szenario mit einem UI 500-Fehler fehl. Aktualisieren Sie die App-Liste als Workaround.

ifdef::azure[]



== Azure Backup-Buckets verwenden standardmäßig LRS-Redundanz

Standardmäßig verwendet der Buckets Astra Control Service für das Speichern von Azure Kubernetes Service-Backups die LRS-Redundanzoption (lokal Redundant Storage). Informationen zur Verwendung einer haltbareren Redundanzoption für Azure Buckets finden Sie in den optionalen Schritten in der Setup-Anleitung für Azure Cloud-Provider:

* link:../get-started/set-up-microsoft-azure-with-amd.html["Richten Sie Microsoft Azure mit von Azure gemanagten Festplatten ein"]
* link:../get-started/set-up-microsoft-azure-with-anf.html["Microsoft Azure mit Azure NetApp Files einrichten"]


endif::azure[]



== Snapshots beginnen schließlich beim Einsatz von External-Snapshotter Version 4.2.0 fehlschlagen

Wenn Sie Kubernetes Snapshot-Controller (auch bekannt als externer Snapshot) Version 4.2.0 mit Kubernetes 1.20 oder 1.21 verwenden, können Snapshots irgendwann fehlschlagen. Um dies zu verhindern, verwenden Sie ein anderes https://kubernetes-csi.github.io/docs/snapshot-controller.html["Unterstützte Version"^] Von externen Snapshots, wie Version 4.2.1, mit Kubernetes Versionen 1.20 oder 1.21.



== Das Management der App-Daten schlägt mit Fehler des internen Service (500) fehl, wenn Astra Trident offline ist

Wenn Astra Trident auf einem App-Cluster offline geschaltet wird (und wieder online geschaltet wird) und 500 interne Servicefehler auftreten, wenn versucht wird, das App-Datenmanagement zu managen, starten Sie alle Kubernetes-Nodes im App-Cluster neu, um die Funktionalität wiederherzustellen.
